defmodule Minga.Config.Writer do
  @moduledoc """
  Debounced writer for settings changed from native GUI frontends.

  GUI settings are persisted to `gui_settings.exs`, a generated overlay loaded after the user's main config and before `after.exs`. This keeps hand-written config intact while still making native settings survive restarts.
  """

  use GenServer

  alias Minga.Config.Loader
  alias Minga.Config.Options

  @debounce_ms 500
  @generated_header "# Generated by Minga's native Settings UI. Do not edit by hand unless Minga is closed.\nuse Minga.Config\n\n"

  @type option_name :: Options.option_name()
  @type state :: %{
          path: String.t(),
          values: %{option_name() => term()},
          timer: reference() | nil,
          debounce_ms: pos_integer(),
          reloading?: boolean(),
          dirty?: boolean()
        }

  @doc "Starts the GUI settings writer."
  @spec start_link(keyword()) :: GenServer.on_start()
  def start_link(opts \\ []) do
    case Keyword.pop(opts, :name, __MODULE__) do
      {nil, opts} -> GenServer.start_link(__MODULE__, opts, [])
      {name, opts} -> GenServer.start_link(__MODULE__, opts, name: name)
    end
  end

  @doc "Persists an option changed by the GUI settings panel after the debounce window."
  @spec persist(option_name(), term()) :: :ok
  @spec persist(GenServer.server(), option_name(), term()) :: :ok
  def persist(name, value) when is_atom(name), do: persist(__MODULE__, name, value)

  def persist(server, name, value) when is_atom(name) do
    GenServer.call(server, {:persist, name, value})
  catch
    :exit, _ -> :ok
  end

  @doc "Marks whether config reload is in progress so pending GUI writes cannot race reload."
  @spec set_reloading(boolean()) :: :ok
  @spec set_reloading(GenServer.server(), boolean()) :: :ok
  def set_reloading(reloading?) when is_boolean(reloading?),
    do: set_reloading(__MODULE__, reloading?)

  def set_reloading(server, reloading?) when is_boolean(reloading?) do
    GenServer.call(server, {:set_reloading, reloading?})
  catch
    :exit, _ -> :ok
  end

  @doc "Returns true when a debounce timer is scheduled for a pending flush."
  @spec pending?(GenServer.server()) :: boolean()
  def pending?(server \\ __MODULE__) do
    GenServer.call(server, :pending?)
  end

  @doc "Flushes pending writes immediately. Intended for tests and clean shutdown paths."
  @spec flush() :: :ok
  @spec flush(GenServer.server()) :: :ok
  def flush, do: flush(__MODULE__)

  def flush(server) do
    GenServer.call(server, :flush)
  catch
    :exit, _ -> :ok
  end

  @impl true
  @spec init(keyword()) :: {:ok, state()}
  def init(opts) do
    Process.flag(:trap_exit, true)
    path = Keyword.get_lazy(opts, :path, &Loader.gui_settings_path/0)
    debounce_ms = Keyword.get(opts, :debounce_ms, @debounce_ms)

    {:ok,
     %{
       path: path,
       values: read_existing_values(path),
       timer: nil,
       debounce_ms: debounce_ms,
       reloading?: false,
       dirty?: false
     }}
  end

  @impl true
  def handle_call({:persist, name, value}, _from, state) do
    values = Map.put(state.values, name, value)
    state = %{state | values: values, dirty?: true}
    {:reply, :ok, schedule_flush(state)}
  end

  def handle_call({:set_reloading, reloading?}, _from, state) do
    {:reply, :ok, set_reloading_state(state, reloading?)}
  end

  def handle_call(:pending?, _from, state) do
    {:reply, state.timer != nil, state}
  end

  def handle_call(:flush, _from, state) do
    state = cancel_timer(state)
    {:reply, :ok, flush_state(state)}
  end

  @impl true
  def handle_info(:flush, state) do
    {:noreply, flush_state(%{state | timer: nil})}
  end

  @impl true
  def terminate(_reason, state) do
    if state.dirty? and not state.reloading? do
      state
      |> cancel_timer()
      |> flush_state()
    end

    :ok
  end

  @spec set_reloading_state(state(), boolean()) :: state()
  defp set_reloading_state(%{dirty?: true} = state, true) do
    state
    |> cancel_timer()
    |> flush_state()
    |> Map.put(:reloading?, true)
  end

  defp set_reloading_state(state, true), do: %{state | reloading?: true}

  defp set_reloading_state(%{dirty?: true, timer: nil} = state, false) do
    state
    |> Map.put(:reloading?, false)
    |> schedule_flush()
  end

  defp set_reloading_state(state, false), do: %{state | reloading?: false}

  @spec schedule_flush(state()) :: state()
  defp schedule_flush(%{reloading?: true} = state), do: state

  defp schedule_flush(state) do
    state = cancel_timer(state)
    timer = Process.send_after(self(), :flush, state.debounce_ms)
    %{state | timer: timer}
  end

  @spec cancel_timer(state()) :: state()
  defp cancel_timer(%{timer: nil} = state), do: state

  defp cancel_timer(%{timer: timer} = state) do
    Process.cancel_timer(timer)

    receive do
      :flush -> :ok
    after
      0 -> :ok
    end

    %{state | timer: nil}
  end

  @spec flush_state(state()) :: state()
  defp flush_state(%{reloading?: true} = state), do: state

  defp flush_state(%{path: path, values: values} = state) do
    case write_values(path, values) do
      :ok ->
        %{state | dirty?: false}

      {:error, reason} ->
        Minga.Log.warning(
          :config,
          "Failed to write GUI settings overlay #{path}: #{inspect(reason)}"
        )

        state
    end
  end

  @spec write_values(String.t(), %{option_name() => term()}) :: :ok | {:error, term()}
  defp write_values(path, values) do
    body =
      values
      |> Enum.sort_by(fn {name, _value} -> Atom.to_string(name) end)
      |> Enum.map(fn {name, value} -> "set :#{name}, #{format_value(value)}\n" end)
      |> IO.iodata_to_binary()

    content = @generated_header <> body
    tmp_path = path <> ".tmp"

    with :ok <- File.mkdir_p(Path.dirname(path)),
         :ok <- File.write(tmp_path, content),
         :ok <- File.rename(tmp_path, path) do
      :ok
    else
      {:error, reason} ->
        File.rm(tmp_path)
        {:error, reason}
    end
  end

  @spec read_existing_values(String.t()) :: %{option_name() => term()}
  defp read_existing_values(path) do
    case File.read(path) do
      {:ok, content} -> parse_existing_values(content)
      {:error, _reason} -> %{}
    end
  end

  @spec parse_existing_values(String.t()) :: %{option_name() => term()}
  defp parse_existing_values(content) do
    ~r/^\s*set\s+:([a-zA-Z0-9_!?]+)\s*,\s*(.+?)\s*$/m
    |> Regex.scan(content)
    |> Enum.reduce(%{}, fn [_line, name, value_text], acc ->
      put_existing_value(acc, name, value_text)
    end)
  end

  @spec put_existing_value(map(), String.t(), String.t()) :: map()
  defp put_existing_value(acc, name_text, value_text) do
    with {:ok, name} <- existing_option_name(name_text),
         {value, _binding} <- Code.eval_string(value_text),
         :ok <- Options.validate_option(name, value) do
      Map.put(acc, name, value)
    else
      _ -> acc
    end
  rescue
    _ -> acc
  end

  @spec existing_option_name(String.t()) :: {:ok, option_name()} | :error
  defp existing_option_name(name_text) do
    name = String.to_existing_atom(name_text)

    if name in Options.valid_names() do
      {:ok, name}
    else
      :error
    end
  rescue
    ArgumentError -> :error
  end

  @spec format_value(term()) :: String.t()
  defp format_value(value) when is_boolean(value), do: inspect(value)
  defp format_value(value) when is_atom(value), do: inspect(value)
  defp format_value(value) when is_binary(value), do: inspect(value)
  defp format_value(value) when is_integer(value), do: Integer.to_string(value)
  defp format_value(value) when is_float(value), do: Float.to_string(value)
  defp format_value(value), do: inspect(value, limit: :infinity)
end
