//! Generated protocol schema assertions.
//!
//! Generated from `docs/protocol_schema.toml` by `mix protocol.gen`. Do not edit by hand.

const std = @import("std");
const protocol = @import("protocol.zig");
const opcodes = @import("protocol_opcodes.zig");

test "generated opcode constants match schema" {
    try std.testing.expectEqual(@as(u8, 0x01), opcodes.OP_KEY_PRESS);
    try std.testing.expectEqual(@as(u8, 0x02), opcodes.OP_RESIZE);
    try std.testing.expectEqual(@as(u8, 0x03), opcodes.OP_READY);
    try std.testing.expectEqual(@as(u8, 0x04), opcodes.OP_MOUSE_EVENT);
    try std.testing.expectEqual(@as(u8, 0x05), opcodes.OP_CAPABILITIES_UPDATED);
    try std.testing.expectEqual(@as(u8, 0x06), opcodes.OP_PASTE_EVENT);
    try std.testing.expectEqual(@as(u8, 0x07), opcodes.OP_GUI_ACTION);
    try std.testing.expectEqual(@as(u8, 0x60), opcodes.OP_LOG_MESSAGE);
    try std.testing.expectEqual(@as(u8, 0x10), opcodes.OP_DRAW_TEXT);
    try std.testing.expectEqual(@as(u8, 0x11), opcodes.OP_SET_CURSOR);
    try std.testing.expectEqual(@as(u8, 0x12), opcodes.OP_CLEAR);
    try std.testing.expectEqual(@as(u8, 0x13), opcodes.OP_BATCH_END);
    try std.testing.expectEqual(@as(u8, 0x14), opcodes.OP_DEFINE_REGION);
    try std.testing.expectEqual(@as(u8, 0x15), opcodes.OP_SET_CURSOR_SHAPE);
    try std.testing.expectEqual(@as(u8, 0x16), opcodes.OP_SET_TITLE);
    try std.testing.expectEqual(@as(u8, 0x17), opcodes.OP_SET_WINDOW_BG);
    try std.testing.expectEqual(@as(u8, 0x18), opcodes.OP_CLEAR_REGION);
    try std.testing.expectEqual(@as(u8, 0x19), opcodes.OP_DESTROY_REGION);
    try std.testing.expectEqual(@as(u8, 0x1A), opcodes.OP_SET_ACTIVE_REGION);
    try std.testing.expectEqual(@as(u8, 0x1B), opcodes.OP_SCROLL_REGION);
    try std.testing.expectEqual(@as(u8, 0x1C), opcodes.OP_DRAW_STYLED_TEXT);
    try std.testing.expectEqual(@as(u8, 0x50), opcodes.OP_SET_FONT);
    try std.testing.expectEqual(@as(u8, 0x51), opcodes.OP_SET_FONT_FALLBACK);
    try std.testing.expectEqual(@as(u8, 0x52), opcodes.OP_REGISTER_FONT);
    try std.testing.expectEqual(@as(u8, 0x20), opcodes.OP_SET_LANGUAGE);
    try std.testing.expectEqual(@as(u8, 0x21), opcodes.OP_PARSE_BUFFER);
    try std.testing.expectEqual(@as(u8, 0x22), opcodes.OP_SET_HIGHLIGHT_QUERY);
    try std.testing.expectEqual(@as(u8, 0x23), opcodes.OP_LOAD_GRAMMAR);
    try std.testing.expectEqual(@as(u8, 0x24), opcodes.OP_SET_INJECTION_QUERY);
    try std.testing.expectEqual(@as(u8, 0x25), opcodes.OP_QUERY_LANGUAGE_AT);
    try std.testing.expectEqual(@as(u8, 0x26), opcodes.OP_EDIT_BUFFER);
    try std.testing.expectEqual(@as(u8, 0x27), opcodes.OP_MEASURE_TEXT);
    try std.testing.expectEqual(@as(u8, 0x28), opcodes.OP_SET_FOLD_QUERY);
    try std.testing.expectEqual(@as(u8, 0x29), opcodes.OP_SET_INDENT_QUERY);
    try std.testing.expectEqual(@as(u8, 0x2A), opcodes.OP_REQUEST_INDENT);
    try std.testing.expectEqual(@as(u8, 0x2B), opcodes.OP_SET_TEXTOBJECT_QUERY);
    try std.testing.expectEqual(@as(u8, 0x2C), opcodes.OP_REQUEST_TEXTOBJECT);
    try std.testing.expectEqual(@as(u8, 0x2D), opcodes.OP_CLOSE_BUFFER);
    try std.testing.expectEqual(@as(u8, 0x2E), opcodes.OP_REQUEST_MATCH_ITEM);
    try std.testing.expectEqual(@as(u8, 0x2F), opcodes.OP_REQUEST_STRUCTURAL_NAV);
    try std.testing.expectEqual(@as(u8, 0x40), opcodes.OP_SET_TAGS_QUERY);
    try std.testing.expectEqual(@as(u8, 0x30), opcodes.OP_HIGHLIGHT_SPANS);
    try std.testing.expectEqual(@as(u8, 0x31), opcodes.OP_HIGHLIGHT_NAMES);
    try std.testing.expectEqual(@as(u8, 0x32), opcodes.OP_GRAMMAR_LOADED);
    try std.testing.expectEqual(@as(u8, 0x33), opcodes.OP_LANGUAGE_AT_RESPONSE);
    try std.testing.expectEqual(@as(u8, 0x34), opcodes.OP_INJECTION_RANGES);
    try std.testing.expectEqual(@as(u8, 0x35), opcodes.OP_TEXT_WIDTH);
    try std.testing.expectEqual(@as(u8, 0x36), opcodes.OP_FOLD_RANGES);
    try std.testing.expectEqual(@as(u8, 0x37), opcodes.OP_INDENT_RESULT);
    try std.testing.expectEqual(@as(u8, 0x38), opcodes.OP_TEXTOBJECT_RESULT);
    try std.testing.expectEqual(@as(u8, 0x39), opcodes.OP_TEXTOBJECT_POSITIONS);
    try std.testing.expectEqual(@as(u8, 0x3A), opcodes.OP_CONCEAL_SPANS);
    try std.testing.expectEqual(@as(u8, 0x3B), opcodes.OP_REQUEST_REPARSE);
    try std.testing.expectEqual(@as(u8, 0x3C), opcodes.OP_MATCH_ITEM_RESULT);
    try std.testing.expectEqual(@as(u8, 0x3D), opcodes.OP_NODE_INFO);
    try std.testing.expectEqual(@as(u8, 0x3E), opcodes.OP_DOCUMENT_SYMBOLS);
    try std.testing.expectEqual(@as(u8, 0x71), opcodes.OP_GUI_TAB_BAR);
    try std.testing.expectEqual(@as(u8, 0x72), opcodes.OP_GUI_WHICH_KEY);
    try std.testing.expectEqual(@as(u8, 0x73), opcodes.OP_GUI_COMPLETION);
    try std.testing.expectEqual(@as(u8, 0x74), opcodes.OP_GUI_THEME);
    try std.testing.expectEqual(@as(u8, 0x75), opcodes.OP_GUI_BREADCRUMB);
    try std.testing.expectEqual(@as(u8, 0x76), opcodes.OP_GUI_STATUS_BAR);
    try std.testing.expectEqual(@as(u8, 0x77), opcodes.OP_GUI_PICKER);
    try std.testing.expectEqual(@as(u8, 0x78), opcodes.OP_GUI_AGENT_CHAT);
    try std.testing.expectEqual(@as(u8, 0x79), opcodes.OP_GUI_GUTTER_SEP);
    try std.testing.expectEqual(@as(u8, 0x7A), opcodes.OP_GUI_CURSORLINE);
    try std.testing.expectEqual(@as(u8, 0x7B), opcodes.OP_GUI_GUTTER);
    try std.testing.expectEqual(@as(u8, 0x7C), opcodes.OP_GUI_BOTTOM_PANEL);
    try std.testing.expectEqual(@as(u8, 0x7D), opcodes.OP_GUI_PICKER_PREVIEW);
    try std.testing.expectEqual(@as(u8, 0x7E), opcodes.OP_GUI_TOOL_MANAGER);
    try std.testing.expectEqual(@as(u8, 0x7F), opcodes.OP_GUI_MINIBUFFER);
    try std.testing.expectEqual(@as(u8, 0x90), opcodes.OP_CLIPBOARD_WRITE);
    try std.testing.expectEqual(@as(u8, 0x91), opcodes.OP_GUI_INDENT_GUIDES);
    try std.testing.expectEqual(@as(u8, 0x92), opcodes.OP_GUI_LINE_SPACING);
    try std.testing.expectEqual(@as(u8, 0x93), opcodes.OP_GUI_FILE_TREE);
    try std.testing.expectEqual(@as(u8, 0x94), opcodes.OP_GUI_FILE_TREE_SELECTION);
    try std.testing.expectEqual(@as(u8, 0x95), opcodes.OP_GUI_CURSOR_ANIMATION);
    try std.testing.expectEqual(@as(u8, 0x80), opcodes.OP_GUI_WINDOW_CONTENT);
    try std.testing.expectEqual(@as(u8, 0x81), opcodes.OP_GUI_HOVER_POPUP);
    try std.testing.expectEqual(@as(u8, 0x82), opcodes.OP_GUI_SIGNATURE_HELP);
    try std.testing.expectEqual(@as(u8, 0x83), opcodes.OP_GUI_FLOAT_POPUP);
    try std.testing.expectEqual(@as(u8, 0x84), opcodes.OP_GUI_SPLIT_SEPARATORS);
    try std.testing.expectEqual(@as(u8, 0x85), opcodes.OP_GUI_GIT_STATUS);
    try std.testing.expectEqual(@as(u8, 0x86), opcodes.OP_GUI_AGENT_GROUPS);
    try std.testing.expectEqual(@as(u8, 0x87), opcodes.OP_GUI_BOARD);
    try std.testing.expectEqual(@as(u8, 0x88), opcodes.OP_GUI_AGENT_CONTEXT);
    try std.testing.expectEqual(@as(u8, 0x89), opcodes.OP_GUI_CHANGE_SUMMARY);
    try std.testing.expectEqual(@as(u8, 0x96), opcodes.OP_GUI_HOVER_ACTION);
    try std.testing.expectEqual(@as(u8, 0x97), opcodes.OP_GUI_CONFIG_STATE);
    try std.testing.expectEqual(@as(u8, 0x01), opcodes.GUI_ACTION_SELECT_TAB);
    try std.testing.expectEqual(@as(u8, 0x02), opcodes.GUI_ACTION_CLOSE_TAB);
    try std.testing.expectEqual(@as(u8, 0x03), opcodes.GUI_ACTION_FILE_TREE_CLICK);
    try std.testing.expectEqual(@as(u8, 0x04), opcodes.GUI_ACTION_FILE_TREE_TOGGLE);
    try std.testing.expectEqual(@as(u8, 0x05), opcodes.GUI_ACTION_COMPLETION_SELECT);
    try std.testing.expectEqual(@as(u8, 0x06), opcodes.GUI_ACTION_BREADCRUMB_CLICK);
    try std.testing.expectEqual(@as(u8, 0x07), opcodes.GUI_ACTION_TOGGLE_PANEL);
    try std.testing.expectEqual(@as(u8, 0x08), opcodes.GUI_ACTION_NEW_TAB);
    try std.testing.expectEqual(@as(u8, 0x09), opcodes.GUI_ACTION_PANEL_SWITCH_TAB);
    try std.testing.expectEqual(@as(u8, 0x0A), opcodes.GUI_ACTION_PANEL_DISMISS);
    try std.testing.expectEqual(@as(u8, 0x0B), opcodes.GUI_ACTION_PANEL_RESIZE);
    try std.testing.expectEqual(@as(u8, 0x0C), opcodes.GUI_ACTION_OPEN_FILE);
    try std.testing.expectEqual(@as(u8, 0x0D), opcodes.GUI_ACTION_FILE_TREE_NEW_FILE);
    try std.testing.expectEqual(@as(u8, 0x0E), opcodes.GUI_ACTION_FILE_TREE_NEW_FOLDER);
    try std.testing.expectEqual(@as(u8, 0x0F), opcodes.GUI_ACTION_FILE_TREE_COLLAPSE_ALL);
    try std.testing.expectEqual(@as(u8, 0x10), opcodes.GUI_ACTION_FILE_TREE_REFRESH);
    try std.testing.expectEqual(@as(u8, 0x11), opcodes.GUI_ACTION_TOOL_INSTALL);
    try std.testing.expectEqual(@as(u8, 0x12), opcodes.GUI_ACTION_TOOL_UNINSTALL);
    try std.testing.expectEqual(@as(u8, 0x13), opcodes.GUI_ACTION_TOOL_UPDATE);
    try std.testing.expectEqual(@as(u8, 0x14), opcodes.GUI_ACTION_TOOL_DISMISS);
    try std.testing.expectEqual(@as(u8, 0x15), opcodes.GUI_ACTION_AGENT_TOOL_TOGGLE);
    try std.testing.expectEqual(@as(u8, 0x16), opcodes.GUI_ACTION_EXECUTE_COMMAND);
    try std.testing.expectEqual(@as(u8, 0x17), opcodes.GUI_ACTION_MINIBUFFER_SELECT);
    try std.testing.expectEqual(@as(u8, 0x18), opcodes.GUI_ACTION_GIT_STAGE_FILE);
    try std.testing.expectEqual(@as(u8, 0x19), opcodes.GUI_ACTION_GIT_UNSTAGE_FILE);
    try std.testing.expectEqual(@as(u8, 0x1A), opcodes.GUI_ACTION_GIT_DISCARD_FILE);
    try std.testing.expectEqual(@as(u8, 0x1B), opcodes.GUI_ACTION_GIT_STAGE_ALL);
    try std.testing.expectEqual(@as(u8, 0x1C), opcodes.GUI_ACTION_GIT_UNSTAGE_ALL);
    try std.testing.expectEqual(@as(u8, 0x1D), opcodes.GUI_ACTION_GIT_COMMIT);
    try std.testing.expectEqual(@as(u8, 0x1E), opcodes.GUI_ACTION_GIT_OPEN_FILE);
    try std.testing.expectEqual(@as(u8, 0x1F), opcodes.GUI_ACTION_AGENT_GROUP_RENAME);
    try std.testing.expectEqual(@as(u8, 0x20), opcodes.GUI_ACTION_AGENT_GROUP_SET_ICON);
    try std.testing.expectEqual(@as(u8, 0x21), opcodes.GUI_ACTION_AGENT_GROUP_CLOSE);
    try std.testing.expectEqual(@as(u8, 0x22), opcodes.GUI_ACTION_SPACE_LEADER_CHORD);
    try std.testing.expectEqual(@as(u8, 0x23), opcodes.GUI_ACTION_SPACE_LEADER_RETRACT);
    try std.testing.expectEqual(@as(u8, 0x24), opcodes.GUI_ACTION_FIND_PASTEBOARD_SEARCH);
    try std.testing.expectEqual(@as(u8, 0x25), opcodes.GUI_ACTION_BOARD_SELECT_CARD);
    try std.testing.expectEqual(@as(u8, 0x26), opcodes.GUI_ACTION_BOARD_CLOSE_CARD);
    try std.testing.expectEqual(@as(u8, 0x27), opcodes.GUI_ACTION_BOARD_REORDER);
    try std.testing.expectEqual(@as(u8, 0x28), opcodes.GUI_ACTION_BOARD_DISPATCH_AGENT);
    try std.testing.expectEqual(@as(u8, 0x29), opcodes.GUI_ACTION_AGENT_APPROVE);
    try std.testing.expectEqual(@as(u8, 0x2A), opcodes.GUI_ACTION_AGENT_REQUEST_CHANGES);
    try std.testing.expectEqual(@as(u8, 0x2B), opcodes.GUI_ACTION_AGENT_DISMISS);
    try std.testing.expectEqual(@as(u8, 0x2C), opcodes.GUI_ACTION_CHANGE_SUMMARY_CLICK);
    try std.testing.expectEqual(@as(u8, 0x2D), opcodes.GUI_ACTION_FILE_TREE_EDIT_CONFIRM);
    try std.testing.expectEqual(@as(u8, 0x2E), opcodes.GUI_ACTION_FILE_TREE_EDIT_CANCEL);
    try std.testing.expectEqual(@as(u8, 0x2F), opcodes.GUI_ACTION_SCROLL_TO_LINE);
    try std.testing.expectEqual(@as(u8, 0x30), opcodes.GUI_ACTION_FILE_TREE_DELETE);
    try std.testing.expectEqual(@as(u8, 0x31), opcodes.GUI_ACTION_FILE_TREE_RENAME);
    try std.testing.expectEqual(@as(u8, 0x32), opcodes.GUI_ACTION_FILE_TREE_DUPLICATE);
    try std.testing.expectEqual(@as(u8, 0x33), opcodes.GUI_ACTION_FILE_TREE_MOVE);
    try std.testing.expectEqual(@as(u8, 0x34), opcodes.GUI_ACTION_SYSTEM_WILL_SLEEP);
    try std.testing.expectEqual(@as(u8, 0x35), opcodes.GUI_ACTION_SYSTEM_DID_WAKE);
    try std.testing.expectEqual(@as(u8, 0x36), opcodes.GUI_ACTION_CMD_COPY);
    try std.testing.expectEqual(@as(u8, 0x37), opcodes.GUI_ACTION_CMD_CUT);
    try std.testing.expectEqual(@as(u8, 0x38), opcodes.GUI_ACTION_GIT_PUSH);
    try std.testing.expectEqual(@as(u8, 0x39), opcodes.GUI_ACTION_GIT_PULL);
    try std.testing.expectEqual(@as(u8, 0x3A), opcodes.GUI_ACTION_GIT_FETCH);
    try std.testing.expectEqual(@as(u8, 0x3B), opcodes.GUI_ACTION_GIT_COMMIT_AMEND);
    try std.testing.expectEqual(@as(u8, 0x3C), opcodes.GUI_ACTION_GIT_PULL_AND_RETRY);
    try std.testing.expectEqual(@as(u8, 0x3D), opcodes.GUI_ACTION_FILE_TREE_OPEN_IN_SPLIT);
    try std.testing.expectEqual(@as(u8, 0x3E), opcodes.GUI_ACTION_TAB_COPY_PATH);
    try std.testing.expectEqual(@as(u8, 0x3F), opcodes.GUI_ACTION_HOVER_OPEN_ACTION);
    try std.testing.expectEqual(@as(u8, 0x40), opcodes.GUI_ACTION_FILE_TREE_DROP);
    try std.testing.expectEqual(@as(u8, 0x41), opcodes.GUI_ACTION_FOLD_TOGGLE_AT_LINE);
    try std.testing.expectEqual(@as(u8, 0x42), opcodes.GUI_ACTION_GIT_OPEN_DIFF);
    try std.testing.expectEqual(@as(u8, 0x43), opcodes.GUI_ACTION_CONFIG_UPDATE);
    try std.testing.expectEqual(@as(u8, 0x44), opcodes.GUI_ACTION_CONFIG_QUERY);
}

test "protocol re-exports generated opcode constants" {
    try std.testing.expectEqual(opcodes.OP_KEY_PRESS, protocol.OP_KEY_PRESS);
    try std.testing.expectEqual(opcodes.OP_RESIZE, protocol.OP_RESIZE);
    try std.testing.expectEqual(opcodes.OP_READY, protocol.OP_READY);
    try std.testing.expectEqual(opcodes.OP_MOUSE_EVENT, protocol.OP_MOUSE_EVENT);
    try std.testing.expectEqual(opcodes.OP_CAPABILITIES_UPDATED, protocol.OP_CAPABILITIES_UPDATED);
    try std.testing.expectEqual(opcodes.OP_PASTE_EVENT, protocol.OP_PASTE_EVENT);
    try std.testing.expectEqual(opcodes.OP_GUI_ACTION, protocol.OP_GUI_ACTION);
    try std.testing.expectEqual(opcodes.OP_LOG_MESSAGE, protocol.OP_LOG_MESSAGE);
    try std.testing.expectEqual(opcodes.OP_DRAW_TEXT, protocol.OP_DRAW_TEXT);
    try std.testing.expectEqual(opcodes.OP_SET_CURSOR, protocol.OP_SET_CURSOR);
    try std.testing.expectEqual(opcodes.OP_CLEAR, protocol.OP_CLEAR);
    try std.testing.expectEqual(opcodes.OP_BATCH_END, protocol.OP_BATCH_END);
    try std.testing.expectEqual(opcodes.OP_DEFINE_REGION, protocol.OP_DEFINE_REGION);
    try std.testing.expectEqual(opcodes.OP_SET_CURSOR_SHAPE, protocol.OP_SET_CURSOR_SHAPE);
    try std.testing.expectEqual(opcodes.OP_SET_TITLE, protocol.OP_SET_TITLE);
    try std.testing.expectEqual(opcodes.OP_SET_WINDOW_BG, protocol.OP_SET_WINDOW_BG);
    try std.testing.expectEqual(opcodes.OP_CLEAR_REGION, protocol.OP_CLEAR_REGION);
    try std.testing.expectEqual(opcodes.OP_DESTROY_REGION, protocol.OP_DESTROY_REGION);
    try std.testing.expectEqual(opcodes.OP_SET_ACTIVE_REGION, protocol.OP_SET_ACTIVE_REGION);
    try std.testing.expectEqual(opcodes.OP_SCROLL_REGION, protocol.OP_SCROLL_REGION);
    try std.testing.expectEqual(opcodes.OP_DRAW_STYLED_TEXT, protocol.OP_DRAW_STYLED_TEXT);
    try std.testing.expectEqual(opcodes.OP_SET_FONT, protocol.OP_SET_FONT);
    try std.testing.expectEqual(opcodes.OP_SET_FONT_FALLBACK, protocol.OP_SET_FONT_FALLBACK);
    try std.testing.expectEqual(opcodes.OP_REGISTER_FONT, protocol.OP_REGISTER_FONT);
    try std.testing.expectEqual(opcodes.OP_SET_LANGUAGE, protocol.OP_SET_LANGUAGE);
    try std.testing.expectEqual(opcodes.OP_PARSE_BUFFER, protocol.OP_PARSE_BUFFER);
    try std.testing.expectEqual(opcodes.OP_SET_HIGHLIGHT_QUERY, protocol.OP_SET_HIGHLIGHT_QUERY);
    try std.testing.expectEqual(opcodes.OP_LOAD_GRAMMAR, protocol.OP_LOAD_GRAMMAR);
    try std.testing.expectEqual(opcodes.OP_SET_INJECTION_QUERY, protocol.OP_SET_INJECTION_QUERY);
    try std.testing.expectEqual(opcodes.OP_QUERY_LANGUAGE_AT, protocol.OP_QUERY_LANGUAGE_AT);
    try std.testing.expectEqual(opcodes.OP_EDIT_BUFFER, protocol.OP_EDIT_BUFFER);
    try std.testing.expectEqual(opcodes.OP_MEASURE_TEXT, protocol.OP_MEASURE_TEXT);
    try std.testing.expectEqual(opcodes.OP_SET_FOLD_QUERY, protocol.OP_SET_FOLD_QUERY);
    try std.testing.expectEqual(opcodes.OP_SET_INDENT_QUERY, protocol.OP_SET_INDENT_QUERY);
    try std.testing.expectEqual(opcodes.OP_REQUEST_INDENT, protocol.OP_REQUEST_INDENT);
    try std.testing.expectEqual(opcodes.OP_SET_TEXTOBJECT_QUERY, protocol.OP_SET_TEXTOBJECT_QUERY);
    try std.testing.expectEqual(opcodes.OP_REQUEST_TEXTOBJECT, protocol.OP_REQUEST_TEXTOBJECT);
    try std.testing.expectEqual(opcodes.OP_CLOSE_BUFFER, protocol.OP_CLOSE_BUFFER);
    try std.testing.expectEqual(opcodes.OP_REQUEST_MATCH_ITEM, protocol.OP_REQUEST_MATCH_ITEM);
    try std.testing.expectEqual(opcodes.OP_REQUEST_STRUCTURAL_NAV, protocol.OP_REQUEST_STRUCTURAL_NAV);
    try std.testing.expectEqual(opcodes.OP_SET_TAGS_QUERY, protocol.OP_SET_TAGS_QUERY);
    try std.testing.expectEqual(opcodes.OP_HIGHLIGHT_SPANS, protocol.OP_HIGHLIGHT_SPANS);
    try std.testing.expectEqual(opcodes.OP_HIGHLIGHT_NAMES, protocol.OP_HIGHLIGHT_NAMES);
    try std.testing.expectEqual(opcodes.OP_GRAMMAR_LOADED, protocol.OP_GRAMMAR_LOADED);
    try std.testing.expectEqual(opcodes.OP_LANGUAGE_AT_RESPONSE, protocol.OP_LANGUAGE_AT_RESPONSE);
    try std.testing.expectEqual(opcodes.OP_INJECTION_RANGES, protocol.OP_INJECTION_RANGES);
    try std.testing.expectEqual(opcodes.OP_TEXT_WIDTH, protocol.OP_TEXT_WIDTH);
    try std.testing.expectEqual(opcodes.OP_FOLD_RANGES, protocol.OP_FOLD_RANGES);
    try std.testing.expectEqual(opcodes.OP_INDENT_RESULT, protocol.OP_INDENT_RESULT);
    try std.testing.expectEqual(opcodes.OP_TEXTOBJECT_RESULT, protocol.OP_TEXTOBJECT_RESULT);
    try std.testing.expectEqual(opcodes.OP_TEXTOBJECT_POSITIONS, protocol.OP_TEXTOBJECT_POSITIONS);
    try std.testing.expectEqual(opcodes.OP_CONCEAL_SPANS, protocol.OP_CONCEAL_SPANS);
    try std.testing.expectEqual(opcodes.OP_REQUEST_REPARSE, protocol.OP_REQUEST_REPARSE);
    try std.testing.expectEqual(opcodes.OP_MATCH_ITEM_RESULT, protocol.OP_MATCH_ITEM_RESULT);
    try std.testing.expectEqual(opcodes.OP_NODE_INFO, protocol.OP_NODE_INFO);
    try std.testing.expectEqual(opcodes.OP_DOCUMENT_SYMBOLS, protocol.OP_DOCUMENT_SYMBOLS);
    try std.testing.expectEqual(opcodes.OP_GUI_TAB_BAR, protocol.OP_GUI_TAB_BAR);
    try std.testing.expectEqual(opcodes.OP_GUI_WHICH_KEY, protocol.OP_GUI_WHICH_KEY);
    try std.testing.expectEqual(opcodes.OP_GUI_COMPLETION, protocol.OP_GUI_COMPLETION);
    try std.testing.expectEqual(opcodes.OP_GUI_THEME, protocol.OP_GUI_THEME);
    try std.testing.expectEqual(opcodes.OP_GUI_BREADCRUMB, protocol.OP_GUI_BREADCRUMB);
    try std.testing.expectEqual(opcodes.OP_GUI_STATUS_BAR, protocol.OP_GUI_STATUS_BAR);
    try std.testing.expectEqual(opcodes.OP_GUI_PICKER, protocol.OP_GUI_PICKER);
    try std.testing.expectEqual(opcodes.OP_GUI_AGENT_CHAT, protocol.OP_GUI_AGENT_CHAT);
    try std.testing.expectEqual(opcodes.OP_GUI_GUTTER_SEP, protocol.OP_GUI_GUTTER_SEP);
    try std.testing.expectEqual(opcodes.OP_GUI_CURSORLINE, protocol.OP_GUI_CURSORLINE);
    try std.testing.expectEqual(opcodes.OP_GUI_GUTTER, protocol.OP_GUI_GUTTER);
    try std.testing.expectEqual(opcodes.OP_GUI_BOTTOM_PANEL, protocol.OP_GUI_BOTTOM_PANEL);
    try std.testing.expectEqual(opcodes.OP_GUI_PICKER_PREVIEW, protocol.OP_GUI_PICKER_PREVIEW);
    try std.testing.expectEqual(opcodes.OP_GUI_TOOL_MANAGER, protocol.OP_GUI_TOOL_MANAGER);
    try std.testing.expectEqual(opcodes.OP_GUI_MINIBUFFER, protocol.OP_GUI_MINIBUFFER);
    try std.testing.expectEqual(opcodes.OP_CLIPBOARD_WRITE, protocol.OP_CLIPBOARD_WRITE);
    try std.testing.expectEqual(opcodes.OP_GUI_INDENT_GUIDES, protocol.OP_GUI_INDENT_GUIDES);
    try std.testing.expectEqual(opcodes.OP_GUI_LINE_SPACING, protocol.OP_GUI_LINE_SPACING);
    try std.testing.expectEqual(opcodes.OP_GUI_FILE_TREE, protocol.OP_GUI_FILE_TREE);
    try std.testing.expectEqual(opcodes.OP_GUI_FILE_TREE_SELECTION, protocol.OP_GUI_FILE_TREE_SELECTION);
    try std.testing.expectEqual(opcodes.OP_GUI_CURSOR_ANIMATION, protocol.OP_GUI_CURSOR_ANIMATION);
    try std.testing.expectEqual(opcodes.OP_GUI_WINDOW_CONTENT, protocol.OP_GUI_WINDOW_CONTENT);
    try std.testing.expectEqual(opcodes.OP_GUI_HOVER_POPUP, protocol.OP_GUI_HOVER_POPUP);
    try std.testing.expectEqual(opcodes.OP_GUI_SIGNATURE_HELP, protocol.OP_GUI_SIGNATURE_HELP);
    try std.testing.expectEqual(opcodes.OP_GUI_FLOAT_POPUP, protocol.OP_GUI_FLOAT_POPUP);
    try std.testing.expectEqual(opcodes.OP_GUI_SPLIT_SEPARATORS, protocol.OP_GUI_SPLIT_SEPARATORS);
    try std.testing.expectEqual(opcodes.OP_GUI_GIT_STATUS, protocol.OP_GUI_GIT_STATUS);
    try std.testing.expectEqual(opcodes.OP_GUI_AGENT_GROUPS, protocol.OP_GUI_AGENT_GROUPS);
    try std.testing.expectEqual(opcodes.OP_GUI_BOARD, protocol.OP_GUI_BOARD);
    try std.testing.expectEqual(opcodes.OP_GUI_AGENT_CONTEXT, protocol.OP_GUI_AGENT_CONTEXT);
    try std.testing.expectEqual(opcodes.OP_GUI_CHANGE_SUMMARY, protocol.OP_GUI_CHANGE_SUMMARY);
    try std.testing.expectEqual(opcodes.OP_GUI_HOVER_ACTION, protocol.OP_GUI_HOVER_ACTION);
    try std.testing.expectEqual(opcodes.OP_GUI_CONFIG_STATE, protocol.OP_GUI_CONFIG_STATE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_SELECT_TAB, protocol.GUI_ACTION_SELECT_TAB);
    try std.testing.expectEqual(opcodes.GUI_ACTION_CLOSE_TAB, protocol.GUI_ACTION_CLOSE_TAB);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_CLICK, protocol.GUI_ACTION_FILE_TREE_CLICK);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_TOGGLE, protocol.GUI_ACTION_FILE_TREE_TOGGLE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_COMPLETION_SELECT, protocol.GUI_ACTION_COMPLETION_SELECT);
    try std.testing.expectEqual(opcodes.GUI_ACTION_BREADCRUMB_CLICK, protocol.GUI_ACTION_BREADCRUMB_CLICK);
    try std.testing.expectEqual(opcodes.GUI_ACTION_TOGGLE_PANEL, protocol.GUI_ACTION_TOGGLE_PANEL);
    try std.testing.expectEqual(opcodes.GUI_ACTION_NEW_TAB, protocol.GUI_ACTION_NEW_TAB);
    try std.testing.expectEqual(opcodes.GUI_ACTION_PANEL_SWITCH_TAB, protocol.GUI_ACTION_PANEL_SWITCH_TAB);
    try std.testing.expectEqual(opcodes.GUI_ACTION_PANEL_DISMISS, protocol.GUI_ACTION_PANEL_DISMISS);
    try std.testing.expectEqual(opcodes.GUI_ACTION_PANEL_RESIZE, protocol.GUI_ACTION_PANEL_RESIZE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_OPEN_FILE, protocol.GUI_ACTION_OPEN_FILE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_NEW_FILE, protocol.GUI_ACTION_FILE_TREE_NEW_FILE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_NEW_FOLDER, protocol.GUI_ACTION_FILE_TREE_NEW_FOLDER);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_COLLAPSE_ALL, protocol.GUI_ACTION_FILE_TREE_COLLAPSE_ALL);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_REFRESH, protocol.GUI_ACTION_FILE_TREE_REFRESH);
    try std.testing.expectEqual(opcodes.GUI_ACTION_TOOL_INSTALL, protocol.GUI_ACTION_TOOL_INSTALL);
    try std.testing.expectEqual(opcodes.GUI_ACTION_TOOL_UNINSTALL, protocol.GUI_ACTION_TOOL_UNINSTALL);
    try std.testing.expectEqual(opcodes.GUI_ACTION_TOOL_UPDATE, protocol.GUI_ACTION_TOOL_UPDATE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_TOOL_DISMISS, protocol.GUI_ACTION_TOOL_DISMISS);
    try std.testing.expectEqual(opcodes.GUI_ACTION_AGENT_TOOL_TOGGLE, protocol.GUI_ACTION_AGENT_TOOL_TOGGLE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_EXECUTE_COMMAND, protocol.GUI_ACTION_EXECUTE_COMMAND);
    try std.testing.expectEqual(opcodes.GUI_ACTION_MINIBUFFER_SELECT, protocol.GUI_ACTION_MINIBUFFER_SELECT);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_STAGE_FILE, protocol.GUI_ACTION_GIT_STAGE_FILE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_UNSTAGE_FILE, protocol.GUI_ACTION_GIT_UNSTAGE_FILE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_DISCARD_FILE, protocol.GUI_ACTION_GIT_DISCARD_FILE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_STAGE_ALL, protocol.GUI_ACTION_GIT_STAGE_ALL);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_UNSTAGE_ALL, protocol.GUI_ACTION_GIT_UNSTAGE_ALL);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_COMMIT, protocol.GUI_ACTION_GIT_COMMIT);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_OPEN_FILE, protocol.GUI_ACTION_GIT_OPEN_FILE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_AGENT_GROUP_RENAME, protocol.GUI_ACTION_AGENT_GROUP_RENAME);
    try std.testing.expectEqual(opcodes.GUI_ACTION_AGENT_GROUP_SET_ICON, protocol.GUI_ACTION_AGENT_GROUP_SET_ICON);
    try std.testing.expectEqual(opcodes.GUI_ACTION_AGENT_GROUP_CLOSE, protocol.GUI_ACTION_AGENT_GROUP_CLOSE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_SPACE_LEADER_CHORD, protocol.GUI_ACTION_SPACE_LEADER_CHORD);
    try std.testing.expectEqual(opcodes.GUI_ACTION_SPACE_LEADER_RETRACT, protocol.GUI_ACTION_SPACE_LEADER_RETRACT);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FIND_PASTEBOARD_SEARCH, protocol.GUI_ACTION_FIND_PASTEBOARD_SEARCH);
    try std.testing.expectEqual(opcodes.GUI_ACTION_BOARD_SELECT_CARD, protocol.GUI_ACTION_BOARD_SELECT_CARD);
    try std.testing.expectEqual(opcodes.GUI_ACTION_BOARD_CLOSE_CARD, protocol.GUI_ACTION_BOARD_CLOSE_CARD);
    try std.testing.expectEqual(opcodes.GUI_ACTION_BOARD_REORDER, protocol.GUI_ACTION_BOARD_REORDER);
    try std.testing.expectEqual(opcodes.GUI_ACTION_BOARD_DISPATCH_AGENT, protocol.GUI_ACTION_BOARD_DISPATCH_AGENT);
    try std.testing.expectEqual(opcodes.GUI_ACTION_AGENT_APPROVE, protocol.GUI_ACTION_AGENT_APPROVE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_AGENT_REQUEST_CHANGES, protocol.GUI_ACTION_AGENT_REQUEST_CHANGES);
    try std.testing.expectEqual(opcodes.GUI_ACTION_AGENT_DISMISS, protocol.GUI_ACTION_AGENT_DISMISS);
    try std.testing.expectEqual(opcodes.GUI_ACTION_CHANGE_SUMMARY_CLICK, protocol.GUI_ACTION_CHANGE_SUMMARY_CLICK);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_EDIT_CONFIRM, protocol.GUI_ACTION_FILE_TREE_EDIT_CONFIRM);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_EDIT_CANCEL, protocol.GUI_ACTION_FILE_TREE_EDIT_CANCEL);
    try std.testing.expectEqual(opcodes.GUI_ACTION_SCROLL_TO_LINE, protocol.GUI_ACTION_SCROLL_TO_LINE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_DELETE, protocol.GUI_ACTION_FILE_TREE_DELETE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_RENAME, protocol.GUI_ACTION_FILE_TREE_RENAME);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_DUPLICATE, protocol.GUI_ACTION_FILE_TREE_DUPLICATE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_MOVE, protocol.GUI_ACTION_FILE_TREE_MOVE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_SYSTEM_WILL_SLEEP, protocol.GUI_ACTION_SYSTEM_WILL_SLEEP);
    try std.testing.expectEqual(opcodes.GUI_ACTION_SYSTEM_DID_WAKE, protocol.GUI_ACTION_SYSTEM_DID_WAKE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_CMD_COPY, protocol.GUI_ACTION_CMD_COPY);
    try std.testing.expectEqual(opcodes.GUI_ACTION_CMD_CUT, protocol.GUI_ACTION_CMD_CUT);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_PUSH, protocol.GUI_ACTION_GIT_PUSH);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_PULL, protocol.GUI_ACTION_GIT_PULL);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_FETCH, protocol.GUI_ACTION_GIT_FETCH);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_COMMIT_AMEND, protocol.GUI_ACTION_GIT_COMMIT_AMEND);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_PULL_AND_RETRY, protocol.GUI_ACTION_GIT_PULL_AND_RETRY);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_OPEN_IN_SPLIT, protocol.GUI_ACTION_FILE_TREE_OPEN_IN_SPLIT);
    try std.testing.expectEqual(opcodes.GUI_ACTION_TAB_COPY_PATH, protocol.GUI_ACTION_TAB_COPY_PATH);
    try std.testing.expectEqual(opcodes.GUI_ACTION_HOVER_OPEN_ACTION, protocol.GUI_ACTION_HOVER_OPEN_ACTION);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FILE_TREE_DROP, protocol.GUI_ACTION_FILE_TREE_DROP);
    try std.testing.expectEqual(opcodes.GUI_ACTION_FOLD_TOGGLE_AT_LINE, protocol.GUI_ACTION_FOLD_TOGGLE_AT_LINE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_GIT_OPEN_DIFF, protocol.GUI_ACTION_GIT_OPEN_DIFF);
    try std.testing.expectEqual(opcodes.GUI_ACTION_CONFIG_UPDATE, protocol.GUI_ACTION_CONFIG_UPDATE);
    try std.testing.expectEqual(opcodes.GUI_ACTION_CONFIG_QUERY, protocol.GUI_ACTION_CONFIG_QUERY);
}

test "protocol exposes generated opcode declarations" {
    comptime {
        if (!@hasDecl(protocol, "OP_KEY_PRESS")) @compileError("missing OP_KEY_PRESS");
        if (!@hasDecl(protocol, "OP_RESIZE")) @compileError("missing OP_RESIZE");
        if (!@hasDecl(protocol, "OP_READY")) @compileError("missing OP_READY");
        if (!@hasDecl(protocol, "OP_MOUSE_EVENT")) @compileError("missing OP_MOUSE_EVENT");
        if (!@hasDecl(protocol, "OP_CAPABILITIES_UPDATED")) @compileError("missing OP_CAPABILITIES_UPDATED");
        if (!@hasDecl(protocol, "OP_PASTE_EVENT")) @compileError("missing OP_PASTE_EVENT");
        if (!@hasDecl(protocol, "OP_GUI_ACTION")) @compileError("missing OP_GUI_ACTION");
        if (!@hasDecl(protocol, "OP_LOG_MESSAGE")) @compileError("missing OP_LOG_MESSAGE");
        if (!@hasDecl(protocol, "OP_DRAW_TEXT")) @compileError("missing OP_DRAW_TEXT");
        if (!@hasDecl(protocol, "OP_SET_CURSOR")) @compileError("missing OP_SET_CURSOR");
        if (!@hasDecl(protocol, "OP_CLEAR")) @compileError("missing OP_CLEAR");
        if (!@hasDecl(protocol, "OP_BATCH_END")) @compileError("missing OP_BATCH_END");
        if (!@hasDecl(protocol, "OP_DEFINE_REGION")) @compileError("missing OP_DEFINE_REGION");
        if (!@hasDecl(protocol, "OP_SET_CURSOR_SHAPE")) @compileError("missing OP_SET_CURSOR_SHAPE");
        if (!@hasDecl(protocol, "OP_SET_TITLE")) @compileError("missing OP_SET_TITLE");
        if (!@hasDecl(protocol, "OP_SET_WINDOW_BG")) @compileError("missing OP_SET_WINDOW_BG");
        if (!@hasDecl(protocol, "OP_CLEAR_REGION")) @compileError("missing OP_CLEAR_REGION");
        if (!@hasDecl(protocol, "OP_DESTROY_REGION")) @compileError("missing OP_DESTROY_REGION");
        if (!@hasDecl(protocol, "OP_SET_ACTIVE_REGION")) @compileError("missing OP_SET_ACTIVE_REGION");
        if (!@hasDecl(protocol, "OP_SCROLL_REGION")) @compileError("missing OP_SCROLL_REGION");
        if (!@hasDecl(protocol, "OP_DRAW_STYLED_TEXT")) @compileError("missing OP_DRAW_STYLED_TEXT");
        if (!@hasDecl(protocol, "OP_SET_FONT")) @compileError("missing OP_SET_FONT");
        if (!@hasDecl(protocol, "OP_SET_FONT_FALLBACK")) @compileError("missing OP_SET_FONT_FALLBACK");
        if (!@hasDecl(protocol, "OP_REGISTER_FONT")) @compileError("missing OP_REGISTER_FONT");
        if (!@hasDecl(protocol, "OP_SET_LANGUAGE")) @compileError("missing OP_SET_LANGUAGE");
        if (!@hasDecl(protocol, "OP_PARSE_BUFFER")) @compileError("missing OP_PARSE_BUFFER");
        if (!@hasDecl(protocol, "OP_SET_HIGHLIGHT_QUERY")) @compileError("missing OP_SET_HIGHLIGHT_QUERY");
        if (!@hasDecl(protocol, "OP_LOAD_GRAMMAR")) @compileError("missing OP_LOAD_GRAMMAR");
        if (!@hasDecl(protocol, "OP_SET_INJECTION_QUERY")) @compileError("missing OP_SET_INJECTION_QUERY");
        if (!@hasDecl(protocol, "OP_QUERY_LANGUAGE_AT")) @compileError("missing OP_QUERY_LANGUAGE_AT");
        if (!@hasDecl(protocol, "OP_EDIT_BUFFER")) @compileError("missing OP_EDIT_BUFFER");
        if (!@hasDecl(protocol, "OP_MEASURE_TEXT")) @compileError("missing OP_MEASURE_TEXT");
        if (!@hasDecl(protocol, "OP_SET_FOLD_QUERY")) @compileError("missing OP_SET_FOLD_QUERY");
        if (!@hasDecl(protocol, "OP_SET_INDENT_QUERY")) @compileError("missing OP_SET_INDENT_QUERY");
        if (!@hasDecl(protocol, "OP_REQUEST_INDENT")) @compileError("missing OP_REQUEST_INDENT");
        if (!@hasDecl(protocol, "OP_SET_TEXTOBJECT_QUERY")) @compileError("missing OP_SET_TEXTOBJECT_QUERY");
        if (!@hasDecl(protocol, "OP_REQUEST_TEXTOBJECT")) @compileError("missing OP_REQUEST_TEXTOBJECT");
        if (!@hasDecl(protocol, "OP_CLOSE_BUFFER")) @compileError("missing OP_CLOSE_BUFFER");
        if (!@hasDecl(protocol, "OP_REQUEST_MATCH_ITEM")) @compileError("missing OP_REQUEST_MATCH_ITEM");
        if (!@hasDecl(protocol, "OP_REQUEST_STRUCTURAL_NAV")) @compileError("missing OP_REQUEST_STRUCTURAL_NAV");
        if (!@hasDecl(protocol, "OP_SET_TAGS_QUERY")) @compileError("missing OP_SET_TAGS_QUERY");
        if (!@hasDecl(protocol, "OP_HIGHLIGHT_SPANS")) @compileError("missing OP_HIGHLIGHT_SPANS");
        if (!@hasDecl(protocol, "OP_HIGHLIGHT_NAMES")) @compileError("missing OP_HIGHLIGHT_NAMES");
        if (!@hasDecl(protocol, "OP_GRAMMAR_LOADED")) @compileError("missing OP_GRAMMAR_LOADED");
        if (!@hasDecl(protocol, "OP_LANGUAGE_AT_RESPONSE")) @compileError("missing OP_LANGUAGE_AT_RESPONSE");
        if (!@hasDecl(protocol, "OP_INJECTION_RANGES")) @compileError("missing OP_INJECTION_RANGES");
        if (!@hasDecl(protocol, "OP_TEXT_WIDTH")) @compileError("missing OP_TEXT_WIDTH");
        if (!@hasDecl(protocol, "OP_FOLD_RANGES")) @compileError("missing OP_FOLD_RANGES");
        if (!@hasDecl(protocol, "OP_INDENT_RESULT")) @compileError("missing OP_INDENT_RESULT");
        if (!@hasDecl(protocol, "OP_TEXTOBJECT_RESULT")) @compileError("missing OP_TEXTOBJECT_RESULT");
        if (!@hasDecl(protocol, "OP_TEXTOBJECT_POSITIONS")) @compileError("missing OP_TEXTOBJECT_POSITIONS");
        if (!@hasDecl(protocol, "OP_CONCEAL_SPANS")) @compileError("missing OP_CONCEAL_SPANS");
        if (!@hasDecl(protocol, "OP_REQUEST_REPARSE")) @compileError("missing OP_REQUEST_REPARSE");
        if (!@hasDecl(protocol, "OP_MATCH_ITEM_RESULT")) @compileError("missing OP_MATCH_ITEM_RESULT");
        if (!@hasDecl(protocol, "OP_NODE_INFO")) @compileError("missing OP_NODE_INFO");
        if (!@hasDecl(protocol, "OP_DOCUMENT_SYMBOLS")) @compileError("missing OP_DOCUMENT_SYMBOLS");
        if (!@hasDecl(protocol, "OP_GUI_TAB_BAR")) @compileError("missing OP_GUI_TAB_BAR");
        if (!@hasDecl(protocol, "OP_GUI_WHICH_KEY")) @compileError("missing OP_GUI_WHICH_KEY");
        if (!@hasDecl(protocol, "OP_GUI_COMPLETION")) @compileError("missing OP_GUI_COMPLETION");
        if (!@hasDecl(protocol, "OP_GUI_THEME")) @compileError("missing OP_GUI_THEME");
        if (!@hasDecl(protocol, "OP_GUI_BREADCRUMB")) @compileError("missing OP_GUI_BREADCRUMB");
        if (!@hasDecl(protocol, "OP_GUI_STATUS_BAR")) @compileError("missing OP_GUI_STATUS_BAR");
        if (!@hasDecl(protocol, "OP_GUI_PICKER")) @compileError("missing OP_GUI_PICKER");
        if (!@hasDecl(protocol, "OP_GUI_AGENT_CHAT")) @compileError("missing OP_GUI_AGENT_CHAT");
        if (!@hasDecl(protocol, "OP_GUI_GUTTER_SEP")) @compileError("missing OP_GUI_GUTTER_SEP");
        if (!@hasDecl(protocol, "OP_GUI_CURSORLINE")) @compileError("missing OP_GUI_CURSORLINE");
        if (!@hasDecl(protocol, "OP_GUI_GUTTER")) @compileError("missing OP_GUI_GUTTER");
        if (!@hasDecl(protocol, "OP_GUI_BOTTOM_PANEL")) @compileError("missing OP_GUI_BOTTOM_PANEL");
        if (!@hasDecl(protocol, "OP_GUI_PICKER_PREVIEW")) @compileError("missing OP_GUI_PICKER_PREVIEW");
        if (!@hasDecl(protocol, "OP_GUI_TOOL_MANAGER")) @compileError("missing OP_GUI_TOOL_MANAGER");
        if (!@hasDecl(protocol, "OP_GUI_MINIBUFFER")) @compileError("missing OP_GUI_MINIBUFFER");
        if (!@hasDecl(protocol, "OP_CLIPBOARD_WRITE")) @compileError("missing OP_CLIPBOARD_WRITE");
        if (!@hasDecl(protocol, "OP_GUI_INDENT_GUIDES")) @compileError("missing OP_GUI_INDENT_GUIDES");
        if (!@hasDecl(protocol, "OP_GUI_LINE_SPACING")) @compileError("missing OP_GUI_LINE_SPACING");
        if (!@hasDecl(protocol, "OP_GUI_FILE_TREE")) @compileError("missing OP_GUI_FILE_TREE");
        if (!@hasDecl(protocol, "OP_GUI_FILE_TREE_SELECTION")) @compileError("missing OP_GUI_FILE_TREE_SELECTION");
        if (!@hasDecl(protocol, "OP_GUI_CURSOR_ANIMATION")) @compileError("missing OP_GUI_CURSOR_ANIMATION");
        if (!@hasDecl(protocol, "OP_GUI_WINDOW_CONTENT")) @compileError("missing OP_GUI_WINDOW_CONTENT");
        if (!@hasDecl(protocol, "OP_GUI_HOVER_POPUP")) @compileError("missing OP_GUI_HOVER_POPUP");
        if (!@hasDecl(protocol, "OP_GUI_SIGNATURE_HELP")) @compileError("missing OP_GUI_SIGNATURE_HELP");
        if (!@hasDecl(protocol, "OP_GUI_FLOAT_POPUP")) @compileError("missing OP_GUI_FLOAT_POPUP");
        if (!@hasDecl(protocol, "OP_GUI_SPLIT_SEPARATORS")) @compileError("missing OP_GUI_SPLIT_SEPARATORS");
        if (!@hasDecl(protocol, "OP_GUI_GIT_STATUS")) @compileError("missing OP_GUI_GIT_STATUS");
        if (!@hasDecl(protocol, "OP_GUI_AGENT_GROUPS")) @compileError("missing OP_GUI_AGENT_GROUPS");
        if (!@hasDecl(protocol, "OP_GUI_BOARD")) @compileError("missing OP_GUI_BOARD");
        if (!@hasDecl(protocol, "OP_GUI_AGENT_CONTEXT")) @compileError("missing OP_GUI_AGENT_CONTEXT");
        if (!@hasDecl(protocol, "OP_GUI_CHANGE_SUMMARY")) @compileError("missing OP_GUI_CHANGE_SUMMARY");
        if (!@hasDecl(protocol, "OP_GUI_HOVER_ACTION")) @compileError("missing OP_GUI_HOVER_ACTION");
        if (!@hasDecl(protocol, "OP_GUI_CONFIG_STATE")) @compileError("missing OP_GUI_CONFIG_STATE");
        if (!@hasDecl(protocol, "GUI_ACTION_SELECT_TAB")) @compileError("missing GUI_ACTION_SELECT_TAB");
        if (!@hasDecl(protocol, "GUI_ACTION_CLOSE_TAB")) @compileError("missing GUI_ACTION_CLOSE_TAB");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_CLICK")) @compileError("missing GUI_ACTION_FILE_TREE_CLICK");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_TOGGLE")) @compileError("missing GUI_ACTION_FILE_TREE_TOGGLE");
        if (!@hasDecl(protocol, "GUI_ACTION_COMPLETION_SELECT")) @compileError("missing GUI_ACTION_COMPLETION_SELECT");
        if (!@hasDecl(protocol, "GUI_ACTION_BREADCRUMB_CLICK")) @compileError("missing GUI_ACTION_BREADCRUMB_CLICK");
        if (!@hasDecl(protocol, "GUI_ACTION_TOGGLE_PANEL")) @compileError("missing GUI_ACTION_TOGGLE_PANEL");
        if (!@hasDecl(protocol, "GUI_ACTION_NEW_TAB")) @compileError("missing GUI_ACTION_NEW_TAB");
        if (!@hasDecl(protocol, "GUI_ACTION_PANEL_SWITCH_TAB")) @compileError("missing GUI_ACTION_PANEL_SWITCH_TAB");
        if (!@hasDecl(protocol, "GUI_ACTION_PANEL_DISMISS")) @compileError("missing GUI_ACTION_PANEL_DISMISS");
        if (!@hasDecl(protocol, "GUI_ACTION_PANEL_RESIZE")) @compileError("missing GUI_ACTION_PANEL_RESIZE");
        if (!@hasDecl(protocol, "GUI_ACTION_OPEN_FILE")) @compileError("missing GUI_ACTION_OPEN_FILE");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_NEW_FILE")) @compileError("missing GUI_ACTION_FILE_TREE_NEW_FILE");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_NEW_FOLDER")) @compileError("missing GUI_ACTION_FILE_TREE_NEW_FOLDER");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_COLLAPSE_ALL")) @compileError("missing GUI_ACTION_FILE_TREE_COLLAPSE_ALL");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_REFRESH")) @compileError("missing GUI_ACTION_FILE_TREE_REFRESH");
        if (!@hasDecl(protocol, "GUI_ACTION_TOOL_INSTALL")) @compileError("missing GUI_ACTION_TOOL_INSTALL");
        if (!@hasDecl(protocol, "GUI_ACTION_TOOL_UNINSTALL")) @compileError("missing GUI_ACTION_TOOL_UNINSTALL");
        if (!@hasDecl(protocol, "GUI_ACTION_TOOL_UPDATE")) @compileError("missing GUI_ACTION_TOOL_UPDATE");
        if (!@hasDecl(protocol, "GUI_ACTION_TOOL_DISMISS")) @compileError("missing GUI_ACTION_TOOL_DISMISS");
        if (!@hasDecl(protocol, "GUI_ACTION_AGENT_TOOL_TOGGLE")) @compileError("missing GUI_ACTION_AGENT_TOOL_TOGGLE");
        if (!@hasDecl(protocol, "GUI_ACTION_EXECUTE_COMMAND")) @compileError("missing GUI_ACTION_EXECUTE_COMMAND");
        if (!@hasDecl(protocol, "GUI_ACTION_MINIBUFFER_SELECT")) @compileError("missing GUI_ACTION_MINIBUFFER_SELECT");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_STAGE_FILE")) @compileError("missing GUI_ACTION_GIT_STAGE_FILE");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_UNSTAGE_FILE")) @compileError("missing GUI_ACTION_GIT_UNSTAGE_FILE");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_DISCARD_FILE")) @compileError("missing GUI_ACTION_GIT_DISCARD_FILE");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_STAGE_ALL")) @compileError("missing GUI_ACTION_GIT_STAGE_ALL");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_UNSTAGE_ALL")) @compileError("missing GUI_ACTION_GIT_UNSTAGE_ALL");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_COMMIT")) @compileError("missing GUI_ACTION_GIT_COMMIT");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_OPEN_FILE")) @compileError("missing GUI_ACTION_GIT_OPEN_FILE");
        if (!@hasDecl(protocol, "GUI_ACTION_AGENT_GROUP_RENAME")) @compileError("missing GUI_ACTION_AGENT_GROUP_RENAME");
        if (!@hasDecl(protocol, "GUI_ACTION_AGENT_GROUP_SET_ICON")) @compileError("missing GUI_ACTION_AGENT_GROUP_SET_ICON");
        if (!@hasDecl(protocol, "GUI_ACTION_AGENT_GROUP_CLOSE")) @compileError("missing GUI_ACTION_AGENT_GROUP_CLOSE");
        if (!@hasDecl(protocol, "GUI_ACTION_SPACE_LEADER_CHORD")) @compileError("missing GUI_ACTION_SPACE_LEADER_CHORD");
        if (!@hasDecl(protocol, "GUI_ACTION_SPACE_LEADER_RETRACT")) @compileError("missing GUI_ACTION_SPACE_LEADER_RETRACT");
        if (!@hasDecl(protocol, "GUI_ACTION_FIND_PASTEBOARD_SEARCH")) @compileError("missing GUI_ACTION_FIND_PASTEBOARD_SEARCH");
        if (!@hasDecl(protocol, "GUI_ACTION_BOARD_SELECT_CARD")) @compileError("missing GUI_ACTION_BOARD_SELECT_CARD");
        if (!@hasDecl(protocol, "GUI_ACTION_BOARD_CLOSE_CARD")) @compileError("missing GUI_ACTION_BOARD_CLOSE_CARD");
        if (!@hasDecl(protocol, "GUI_ACTION_BOARD_REORDER")) @compileError("missing GUI_ACTION_BOARD_REORDER");
        if (!@hasDecl(protocol, "GUI_ACTION_BOARD_DISPATCH_AGENT")) @compileError("missing GUI_ACTION_BOARD_DISPATCH_AGENT");
        if (!@hasDecl(protocol, "GUI_ACTION_AGENT_APPROVE")) @compileError("missing GUI_ACTION_AGENT_APPROVE");
        if (!@hasDecl(protocol, "GUI_ACTION_AGENT_REQUEST_CHANGES")) @compileError("missing GUI_ACTION_AGENT_REQUEST_CHANGES");
        if (!@hasDecl(protocol, "GUI_ACTION_AGENT_DISMISS")) @compileError("missing GUI_ACTION_AGENT_DISMISS");
        if (!@hasDecl(protocol, "GUI_ACTION_CHANGE_SUMMARY_CLICK")) @compileError("missing GUI_ACTION_CHANGE_SUMMARY_CLICK");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_EDIT_CONFIRM")) @compileError("missing GUI_ACTION_FILE_TREE_EDIT_CONFIRM");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_EDIT_CANCEL")) @compileError("missing GUI_ACTION_FILE_TREE_EDIT_CANCEL");
        if (!@hasDecl(protocol, "GUI_ACTION_SCROLL_TO_LINE")) @compileError("missing GUI_ACTION_SCROLL_TO_LINE");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_DELETE")) @compileError("missing GUI_ACTION_FILE_TREE_DELETE");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_RENAME")) @compileError("missing GUI_ACTION_FILE_TREE_RENAME");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_DUPLICATE")) @compileError("missing GUI_ACTION_FILE_TREE_DUPLICATE");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_MOVE")) @compileError("missing GUI_ACTION_FILE_TREE_MOVE");
        if (!@hasDecl(protocol, "GUI_ACTION_SYSTEM_WILL_SLEEP")) @compileError("missing GUI_ACTION_SYSTEM_WILL_SLEEP");
        if (!@hasDecl(protocol, "GUI_ACTION_SYSTEM_DID_WAKE")) @compileError("missing GUI_ACTION_SYSTEM_DID_WAKE");
        if (!@hasDecl(protocol, "GUI_ACTION_CMD_COPY")) @compileError("missing GUI_ACTION_CMD_COPY");
        if (!@hasDecl(protocol, "GUI_ACTION_CMD_CUT")) @compileError("missing GUI_ACTION_CMD_CUT");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_PUSH")) @compileError("missing GUI_ACTION_GIT_PUSH");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_PULL")) @compileError("missing GUI_ACTION_GIT_PULL");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_FETCH")) @compileError("missing GUI_ACTION_GIT_FETCH");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_COMMIT_AMEND")) @compileError("missing GUI_ACTION_GIT_COMMIT_AMEND");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_PULL_AND_RETRY")) @compileError("missing GUI_ACTION_GIT_PULL_AND_RETRY");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_OPEN_IN_SPLIT")) @compileError("missing GUI_ACTION_FILE_TREE_OPEN_IN_SPLIT");
        if (!@hasDecl(protocol, "GUI_ACTION_TAB_COPY_PATH")) @compileError("missing GUI_ACTION_TAB_COPY_PATH");
        if (!@hasDecl(protocol, "GUI_ACTION_HOVER_OPEN_ACTION")) @compileError("missing GUI_ACTION_HOVER_OPEN_ACTION");
        if (!@hasDecl(protocol, "GUI_ACTION_FILE_TREE_DROP")) @compileError("missing GUI_ACTION_FILE_TREE_DROP");
        if (!@hasDecl(protocol, "GUI_ACTION_FOLD_TOGGLE_AT_LINE")) @compileError("missing GUI_ACTION_FOLD_TOGGLE_AT_LINE");
        if (!@hasDecl(protocol, "GUI_ACTION_GIT_OPEN_DIFF")) @compileError("missing GUI_ACTION_GIT_OPEN_DIFF");
        if (!@hasDecl(protocol, "GUI_ACTION_CONFIG_UPDATE")) @compileError("missing GUI_ACTION_CONFIG_UPDATE");
        if (!@hasDecl(protocol, "GUI_ACTION_CONFIG_QUERY")) @compileError("missing GUI_ACTION_CONFIG_QUERY");
    }
}
