%{
  configs: [
    %{
      name: "default",
      strict: true,
      files: %{
        included: ["lib/", "mix/", "test/"],
        excluded: [~r"/_build/", ~r"/deps/", ~r"/test/support/"]
      },
      plugins: [],
      requires: ["credo/checks/*.exs"],
      checks: %{
        enabled: [
          # ── Consistency ────────────────────────────────────────────────────
          {Credo.Check.Consistency.ExceptionNames, []},
          {Credo.Check.Consistency.LineEndings, []},
          {Credo.Check.Consistency.ParameterPatternMatching, []},
          {Credo.Check.Consistency.SpaceAroundOperators, []},
          {Credo.Check.Consistency.SpaceInParentheses, []},
          {Credo.Check.Consistency.TabsOrSpaces, []},

          # ── Design ─────────────────────────────────────────────────────────
          {Credo.Check.Design.AliasUsage, false},
          {Credo.Check.Design.TagFIXME, []},
          {Credo.Check.Design.TagTODO, false},

          # ── Dependency direction ──────────────────────────────────────────
          {Minga.Credo.DependencyDirectionCheck, []},
          {Minga.Credo.NoProcessSleepCheck, []},
          {Minga.Credo.NoDirectLoggerCheck, [exit_status: 0]},
          {Minga.Credo.NoDirectStateMachineWriteCheck, []},
          {Minga.Credo.NoDirectModalOverlayWriteCheck, []},
          {Minga.Credo.NoRawWorkspaceSnapshotCheck, []},
          {Minga.Credo.NoLossyGuiEncoderCheck, []},
          {Minga.Credo.CommandRegistrationCheck, []},
          {Minga.Credo.EditorStateOwnershipCheck, []},

          # ── Editor responsiveness (epic #2445) ─────────────────────────────
          {Minga.Credo.NoBlockingEditorCallCheck, []},
          {Minga.Credo.NoBlockingHandleInfoCheck, []},
          {Minga.Credo.NoDelegateInEditorCheck, [exit_status: 0]},

          # ── Test isolation ────────────────────────────────────────────────
          {Minga.Credo.NoEventBusBroadcastInTestCheck, []},
          {Minga.Credo.NoGlobalStateInTestCheck, [exit_status: 0]},

          # ── Readability ────────────────────────────────────────────────────
          {Credo.Check.Readability.AliasOrder, false},
          {Credo.Check.Readability.FunctionNames, []},
          {Credo.Check.Readability.LargeNumbers, []},
          {Credo.Check.Readability.MaxLineLength, [max_length: 120, priority: :low]},
          {Credo.Check.Readability.ModuleAttributeNames, []},
          {Credo.Check.Readability.ModuleDoc, []},
          {Credo.Check.Readability.ModuleNames, []},
          {Credo.Check.Readability.ParenthesesInCondition, []},
          {Credo.Check.Readability.ParenthesesOnZeroArityDefs, []},
          {Credo.Check.Readability.PipeIntoAnonymousFunctions, []},
          {Credo.Check.Readability.PredicateFunctionNames, []},
          {Credo.Check.Readability.PreferImplicitTry, []},
          {Credo.Check.Readability.RedundantBlankLines, false},
          {Credo.Check.Readability.Semicolons, []},
          {Credo.Check.Readability.SpaceAfterCommas, []},
          {Credo.Check.Readability.Specs, [priority: :high]},
          {Credo.Check.Readability.StringSigils, []},
          {Credo.Check.Readability.TrailingBlankLine, []},
          {Credo.Check.Readability.TrailingWhiteSpace, []},
          {Credo.Check.Readability.UnnecessaryAliasExpansion, []},
          {Credo.Check.Readability.VariableNames, []},
          {Credo.Check.Readability.WithSingleClause, []},

          # ── AI slop readability ───────────────────────────────────────────
          {ExSlop.Check.Readability.NarratorDoc, [exit_status: 0]},
          {ExSlop.Check.Readability.DocFalseOnPublicFunction, [exit_status: 0]},
          {ExSlop.Check.Readability.BoilerplateDocParams, [exit_status: 0]},
          {ExSlop.Check.Readability.ObviousComment, [additional_keywords: [], exit_status: 0]},
          {ExSlop.Check.Readability.StepComment, [exit_status: 0]},
          {ExSlop.Check.Readability.NarratorComment, [exit_status: 0]},
          {ExSlop.Check.Readability.UnaliasedModuleUse, [exit_status: 0]},

          # ── Refactor ───────────────────────────────────────────────────────
          {Credo.Check.Refactor.Apply, []},
          {Credo.Check.Refactor.AppendSingleItem, [exit_status: 0]},
          {Credo.Check.Refactor.CondStatements, []},
          {Credo.Check.Refactor.CyclomaticComplexity, [max_complexity: 12]},
          {Credo.Check.Refactor.DoubleBooleanNegation, []},
          {Credo.Check.Refactor.FilterCount, []},
          {Credo.Check.Refactor.FilterFilter, []},
          {Credo.Check.Refactor.FunctionArity, []},
          {Credo.Check.Refactor.LongQuoteBlocks, []},
          {Credo.Check.Refactor.MapJoin, []},
          {Credo.Check.Refactor.MapMap, [exit_status: 0]},
          {Credo.Check.Refactor.MatchInCondition, []},
          {Credo.Check.Refactor.NegatedConditionsInUnless, []},
          {Credo.Check.Refactor.NegatedConditionsWithElse, []},
          {Credo.Check.Refactor.NegatedIsNil, []},
          {Credo.Check.Refactor.Nesting, []},
          {Credo.Check.Refactor.RedundantWithClauseResult, []},
          {Credo.Check.Refactor.RejectReject, []},
          {Credo.Check.Refactor.UnlessWithElse, []},
          {Credo.Check.Refactor.WithClauses, []},
          {ExSlop.Check.Refactor.FilterNil, [exit_status: 0]},
          {ExSlop.Check.Refactor.RejectNil, [exit_status: 0]},
          {ExSlop.Check.Refactor.ReduceAsMap, [exit_status: 0]},
          {ExSlop.Check.Refactor.MapIntoLiteral, [exit_status: 0]},
          {ExSlop.Check.Refactor.IdentityPassthrough, [exit_status: 0]},
          {ExSlop.Check.Refactor.IdentityMap, [exit_status: 0]},
          {ExSlop.Check.Refactor.CaseTrueFalse, [exit_status: 0]},
          {ExSlop.Check.Refactor.TryRescueWithSafeAlternative, [exit_status: 0]},
          {ExSlop.Check.Refactor.WithIdentityElse, [exit_status: 0]},
          {ExSlop.Check.Refactor.WithIdentityDo, [exit_status: 0]},
          {ExSlop.Check.Refactor.SortThenReverse, [exit_status: 0]},
          {ExSlop.Check.Refactor.StringConcatInReduce, [exit_status: 0]},
          {ExSlop.Check.Refactor.ReduceMapPut, [exit_status: 0]},
          {ExSlop.Check.Refactor.RedundantBooleanIf, [exit_status: 0]},
          {ExSlop.Check.Refactor.FlatMapFilter, [exit_status: 0]},
          {ExSlop.Check.Refactor.RedundantEnumJoinSeparator, [exit_status: 0]},
          {ExSlop.Check.Refactor.UseMapJoin, [exit_status: 0]},
          {ExSlop.Check.Refactor.PreferEnumSlice, [exit_status: 0]},
          {ExSlop.Check.Refactor.GraphemesLength, [exit_status: 0]},
          {ExSlop.Check.Refactor.ManualStringReverse, [exit_status: 0]},
          {ExSlop.Check.Refactor.SortThenAt, [exit_status: 0]},
          {ExSlop.Check.Refactor.SortForTopK, [exit_status: 0]},
          {ExSlop.Check.Refactor.ListFold, [exit_status: 0]},
          {ExSlop.Check.Refactor.ListLast, [exit_status: 0]},
          {ExSlop.Check.Refactor.LengthInGuard, [exit_status: 0]},
          {ExSlop.Check.Refactor.LengthComparison, [exit_status: 0]},
          {ExSlop.Check.Refactor.ExplicitSumReduce, [exit_status: 0]},

          # ── Warnings ───────────────────────────────────────────────────────
          {Credo.Check.Warning.ApplicationConfigInModuleAttribute, []},
          {Credo.Check.Warning.BoolOperationOnSameValues, []},
          {Credo.Check.Warning.Dbg, []},
          {Credo.Check.Warning.ExpensiveEmptyEnumCheck, []},
          {Credo.Check.Warning.IExPry, []},
          {Credo.Check.Warning.IoInspect, []},
          {Credo.Check.Warning.MissedMetadataKeyInLoggerConfig, []},
          {Credo.Check.Warning.MixEnv, []},
          {Credo.Check.Warning.OperationOnSameValues, []},
          {Credo.Check.Warning.OperationWithConstantResult, []},
          {Credo.Check.Warning.RaiseInsideRescue, []},
          {Credo.Check.Warning.SpecWithStruct, []},
          {Credo.Check.Warning.StructFieldAmount, false},
          {Credo.Check.Warning.UnsafeExec, []},
          {Credo.Check.Warning.UnusedEnumOperation, []},
          {Credo.Check.Warning.UnusedFileOperation, []},
          {Credo.Check.Warning.UnusedKeywordOperation, []},
          {Credo.Check.Warning.UnusedListOperation, []},
          {Credo.Check.Warning.UnusedMapOperation, []},
          {Credo.Check.Warning.UnusedPathOperation, []},
          {Credo.Check.Warning.UnusedRegexOperation, []},
          {Credo.Check.Warning.UnusedStringOperation, []},
          {Credo.Check.Warning.UnusedTupleOperation, []},
          {Credo.Check.Warning.WrongTestFileExtension, []},
          {ExSlop.Check.Warning.BlanketRescue, [exit_status: 0]},
          {ExSlop.Check.Warning.RescueWithoutReraise, [exit_status: 0]},
          {ExSlop.Check.Warning.RepoAllThenFilter, [exit_status: 0]},
          {ExSlop.Check.Warning.QueryInEnumMap, [exit_status: 0]},
          {ExSlop.Check.Warning.GenserverAsKvStore, [exit_status: 0]},
          {ExSlop.Check.Warning.PathExpandPriv, [exit_status: 0]},
          {ExSlop.Check.Warning.DualKeyAccess, [exit_status: 0]}
        ]
      }
    }
  ]
}
