/// Port protocol opcode constants and capability values.
///
/// These must match the values in `lib/minga/port/protocol.ex` and
/// `zig/src/protocol.zig`. See `docs/PROTOCOL.md` for the full spec.

// MARK: - Event opcodes (frontend → BEAM)

let OP_KEY_PRESS: UInt8 = 0x01
let OP_RESIZE: UInt8 = 0x02
let OP_READY: UInt8 = 0x03
let OP_MOUSE_EVENT: UInt8 = 0x04
let OP_PASTE_EVENT: UInt8 = 0x06

// MARK: - Render command opcodes (BEAM → frontend)

let OP_DRAW_TEXT: UInt8 = 0x10
let OP_SET_CURSOR: UInt8 = 0x11
let OP_CLEAR: UInt8 = 0x12
let OP_BATCH_END: UInt8 = 0x13
let OP_DEFINE_REGION: UInt8 = 0x14
let OP_SET_CURSOR_SHAPE: UInt8 = 0x15
let OP_SET_TITLE: UInt8 = 0x16
let OP_SET_WINDOW_BG: UInt8 = 0x17
let OP_CLEAR_REGION: UInt8 = 0x18
let OP_DESTROY_REGION: UInt8 = 0x19
let OP_SET_ACTIVE_REGION: UInt8 = 0x1A
let OP_DRAW_STYLED_TEXT: UInt8 = 0x1C

// MARK: - GUI chrome opcodes (BEAM → frontend, contiguous range 0x70-0x7F)

let OP_GUI_FILE_TREE: UInt8 = 0x70
let OP_GUI_TAB_BAR: UInt8 = 0x71
let OP_GUI_WHICH_KEY: UInt8 = 0x72
let OP_GUI_COMPLETION: UInt8 = 0x73
let OP_GUI_THEME: UInt8 = 0x74
let OP_GUI_BREADCRUMB: UInt8 = 0x75
let OP_GUI_STATUS_BAR: UInt8 = 0x76
let OP_GUI_PICKER: UInt8 = 0x77
let OP_GUI_AGENT_CHAT: UInt8 = 0x78
let OP_GUI_GUTTER_SEP: UInt8 = 0x79
let OP_GUI_CURSORLINE: UInt8 = 0x7A
let OP_GUI_GUTTER: UInt8 = 0x7B
let OP_GUI_BOTTOM_PANEL: UInt8 = 0x7C
let OP_GUI_PICKER_PREVIEW: UInt8 = 0x7D
let OP_GUI_TOOL_MANAGER: UInt8 = 0x7E

// GUI window content opcode (semantic rendering data for buffer windows)
let OP_GUI_WINDOW_CONTENT: UInt8 = 0x80

// GUI theme color slot IDs
let GUI_COLOR_EDITOR_BG: UInt8 = 0x01
let GUI_COLOR_EDITOR_FG: UInt8 = 0x02
let GUI_COLOR_TREE_BG: UInt8 = 0x03
let GUI_COLOR_TREE_FG: UInt8 = 0x04
let GUI_COLOR_TREE_SELECTION_BG: UInt8 = 0x05
let GUI_COLOR_TREE_DIR_FG: UInt8 = 0x06
let GUI_COLOR_TREE_ACTIVE_FG: UInt8 = 0x07
let GUI_COLOR_TREE_HEADER_BG: UInt8 = 0x08
let GUI_COLOR_TREE_HEADER_FG: UInt8 = 0x09
let GUI_COLOR_TREE_SEPARATOR_FG: UInt8 = 0x0A
let GUI_COLOR_TREE_GIT_MODIFIED: UInt8 = 0x0B
let GUI_COLOR_TREE_GIT_STAGED: UInt8 = 0x0C
let GUI_COLOR_TREE_GIT_UNTRACKED: UInt8 = 0x0D
let GUI_COLOR_TREE_SELECTION_FG: UInt8 = 0x0E
let GUI_COLOR_TREE_GUIDE_FG: UInt8 = 0x0F
let GUI_COLOR_TAB_BG: UInt8 = 0x10
let GUI_COLOR_TAB_ACTIVE_BG: UInt8 = 0x11
let GUI_COLOR_TAB_ACTIVE_FG: UInt8 = 0x12
let GUI_COLOR_TAB_INACTIVE_FG: UInt8 = 0x13
let GUI_COLOR_TAB_MODIFIED_FG: UInt8 = 0x14
let GUI_COLOR_TAB_SEPARATOR_FG: UInt8 = 0x15
let GUI_COLOR_TAB_CLOSE_HOVER_FG: UInt8 = 0x16
let GUI_COLOR_TAB_ATTENTION_FG: UInt8 = 0x17
let GUI_COLOR_POPUP_BG: UInt8 = 0x20
let GUI_COLOR_POPUP_FG: UInt8 = 0x21
let GUI_COLOR_POPUP_BORDER: UInt8 = 0x22
let GUI_COLOR_POPUP_SEL_BG: UInt8 = 0x23
let GUI_COLOR_POPUP_KEY_FG: UInt8 = 0x24
let GUI_COLOR_POPUP_GROUP_FG: UInt8 = 0x25
let GUI_COLOR_POPUP_DESC_FG: UInt8 = 0x26
let GUI_COLOR_BREADCRUMB_BG: UInt8 = 0x27
let GUI_COLOR_BREADCRUMB_FG: UInt8 = 0x28
let GUI_COLOR_BREADCRUMB_SEPARATOR_FG: UInt8 = 0x29
let GUI_COLOR_MODELINE_BAR_BG: UInt8 = 0x30
let GUI_COLOR_MODELINE_BAR_FG: UInt8 = 0x31
let GUI_COLOR_MODELINE_INFO_BG: UInt8 = 0x32
let GUI_COLOR_MODELINE_INFO_FG: UInt8 = 0x33
let GUI_COLOR_MODE_NORMAL_BG: UInt8 = 0x34
let GUI_COLOR_MODE_NORMAL_FG: UInt8 = 0x35
let GUI_COLOR_MODE_INSERT_BG: UInt8 = 0x36
let GUI_COLOR_MODE_INSERT_FG: UInt8 = 0x37
let GUI_COLOR_MODE_VISUAL_BG: UInt8 = 0x38
let GUI_COLOR_MODE_VISUAL_FG: UInt8 = 0x39
let GUI_COLOR_STATUSBAR_ACCENT_FG: UInt8 = 0x3A
let GUI_COLOR_ACCENT: UInt8 = 0x40

// Gutter + Git color slots
let GUI_COLOR_GUTTER_FG: UInt8 = 0x50
let GUI_COLOR_GUTTER_CURRENT_FG: UInt8 = 0x51
let GUI_COLOR_GUTTER_ERROR_FG: UInt8 = 0x52
let GUI_COLOR_GUTTER_WARNING_FG: UInt8 = 0x53
let GUI_COLOR_GUTTER_INFO_FG: UInt8 = 0x54
let GUI_COLOR_GUTTER_HINT_FG: UInt8 = 0x55
let GUI_COLOR_GIT_ADDED_FG: UInt8 = 0x56
let GUI_COLOR_GIT_MODIFIED_FG: UInt8 = 0x57
let GUI_COLOR_GIT_DELETED_FG: UInt8 = 0x58
let GUI_COLOR_HIGHLIGHT_READ_BG: UInt8 = 0x59
let GUI_COLOR_HIGHLIGHT_WRITE_BG: UInt8 = 0x5A
let GUI_COLOR_SELECTION_BG: UInt8 = 0x5B

// MARK: - Config opcodes (BEAM → frontend)

let OP_SET_FONT: UInt8 = 0x50
let OP_SET_FONT_FALLBACK: UInt8 = 0x51
let OP_REGISTER_FONT: UInt8 = 0x52

// MARK: - Highlight opcodes (ignored by GUI, handled by minga-parser)

let OP_SET_LANGUAGE: UInt8 = 0x20
let OP_PARSE_BUFFER: UInt8 = 0x21
let OP_SET_HIGHLIGHT_QUERY: UInt8 = 0x22
let OP_LOAD_GRAMMAR: UInt8 = 0x23
let OP_SET_INJECTION_QUERY: UInt8 = 0x24
let OP_QUERY_LANGUAGE_AT: UInt8 = 0x25
let OP_EDIT_BUFFER: UInt8 = 0x26
let OP_MEASURE_TEXT: UInt8 = 0x27

// MARK: - Cursor shapes

let CURSOR_BLOCK: UInt8 = 0x00
let CURSOR_BEAM: UInt8 = 0x01
let CURSOR_UNDERLINE: UInt8 = 0x02

// MARK: - Capability constants

let CAPS_VERSION: UInt8 = 1

let FRONTEND_TUI: UInt8 = 0
let FRONTEND_NATIVE_GUI: UInt8 = 1

let COLOR_RGB: UInt8 = 2
let UNICODE_15: UInt8 = 1
let IMAGE_NATIVE: UInt8 = 3
let FLOAT_NATIVE: UInt8 = 1
let TEXT_PROPORTIONAL: UInt8 = 1

// MARK: - Text attribute bits

let ATTR_BOLD: UInt8 = 0x01
let ATTR_UNDERLINE: UInt8 = 0x02
let ATTR_ITALIC: UInt8 = 0x04
let ATTR_REVERSE: UInt8 = 0x08
let ATTR_STRIKETHROUGH: UInt16 = 0x10

// Underline style (3 bits at position 5-7 in extended 16-bit attrs)
let UL_STYLE_SHIFT: UInt16 = 5
let UL_STYLE_MASK: UInt16 = 0x07  // 3 bits
let UL_STYLE_LINE: UInt16 = 0
let UL_STYLE_CURL: UInt16 = 1
let UL_STYLE_DASHED: UInt16 = 2
let UL_STYLE_DOTTED: UInt16 = 3
let UL_STYLE_DOUBLE: UInt16 = 4

// Bold/italic style mask for font variant selection (bits 0 and 2 of attrs)
let FONT_STYLE_MASK: UInt8 = 0x05

// MARK: - Mouse button constants

let MOUSE_BUTTON_LEFT: UInt8 = 0x00
let MOUSE_BUTTON_MIDDLE: UInt8 = 0x01
let MOUSE_BUTTON_RIGHT: UInt8 = 0x02
let MOUSE_BUTTON_NONE: UInt8 = 0x03
let MOUSE_SCROLL_UP: UInt8 = 0x40
let MOUSE_SCROLL_DOWN: UInt8 = 0x41
let MOUSE_SCROLL_RIGHT: UInt8 = 0x42
let MOUSE_SCROLL_LEFT: UInt8 = 0x43

// MARK: - GUI action opcode (frontend → BEAM)

let OP_GUI_ACTION: UInt8 = 0x07

// GUI action types (sub-opcodes within gui_action)
let GUI_ACTION_SELECT_TAB: UInt8 = 0x01
let GUI_ACTION_CLOSE_TAB: UInt8 = 0x02
let GUI_ACTION_FILE_TREE_CLICK: UInt8 = 0x03
let GUI_ACTION_FILE_TREE_TOGGLE: UInt8 = 0x04
let GUI_ACTION_COMPLETION_SELECT: UInt8 = 0x05
let GUI_ACTION_BREADCRUMB_CLICK: UInt8 = 0x06
let GUI_ACTION_TOGGLE_PANEL: UInt8 = 0x07
let GUI_ACTION_NEW_TAB: UInt8 = 0x08
let GUI_ACTION_PANEL_SWITCH_TAB: UInt8 = 0x09
let GUI_ACTION_PANEL_DISMISS: UInt8 = 0x0A
let GUI_ACTION_PANEL_RESIZE: UInt8 = 0x0B
let GUI_ACTION_OPEN_FILE: UInt8 = 0x0C
let GUI_ACTION_FILE_TREE_NEW_FILE: UInt8 = 0x0D
let GUI_ACTION_FILE_TREE_NEW_FOLDER: UInt8 = 0x0E
let GUI_ACTION_FILE_TREE_COLLAPSE_ALL: UInt8 = 0x0F
let GUI_ACTION_FILE_TREE_REFRESH: UInt8 = 0x10
let GUI_ACTION_TOOL_INSTALL: UInt8 = 0x11
let GUI_ACTION_TOOL_UNINSTALL: UInt8 = 0x12
let GUI_ACTION_TOOL_UPDATE: UInt8 = 0x13
let GUI_ACTION_TOOL_DISMISS: UInt8 = 0x14

// MARK: - Log message opcode (frontend → BEAM)

let OP_LOG_MESSAGE: UInt8 = 0x60

// MARK: - Log levels (must match Zig protocol.zig and Elixir protocol.ex)

let LOG_LEVEL_ERR: UInt8 = 0
let LOG_LEVEL_WARN: UInt8 = 1
let LOG_LEVEL_INFO: UInt8 = 2
let LOG_LEVEL_DEBUG: UInt8 = 3

// MARK: - Mouse event types

let MOUSE_PRESS: UInt8 = 0x00
let MOUSE_RELEASE: UInt8 = 0x01
let MOUSE_MOTION: UInt8 = 0x02
let MOUSE_DRAG: UInt8 = 0x03
