/// Port protocol constants that are not opcode values.
///
/// Opcode and GUI action constants are generated in `macos/.generated/protocol/ProtocolOpcodes.generated.swift` from `docs/protocol_schema.toml`.

// MARK: - Sectioned format section IDs
// Used by opcodes with self-describing sections (gui_status_bar, etc.).
// Format: section_id(1) + section_len(2, big-endian) + payload(section_len)

let SECTION_IDENTITY: UInt8 = 0x01
let SECTION_CURSOR: UInt8 = 0x02
let SECTION_DIAGNOSTICS: UInt8 = 0x03
let SECTION_LANGUAGE: UInt8 = 0x04
let SECTION_GIT: UInt8 = 0x05
let SECTION_FILE: UInt8 = 0x06
let SECTION_MESSAGE: UInt8 = 0x07
let SECTION_RECORDING: UInt8 = 0x08
let SECTION_AGENT: UInt8 = 0x09
let SECTION_INDENT: UInt8 = 0x0A
let SECTION_MODELINE_SEGMENTS: UInt8 = 0x0B
let SECTION_SELECTION: UInt8 = 0x0C

// GUI theme color slot IDs
let GUI_COLOR_EDITOR_BG: UInt8 = 0x01
let GUI_COLOR_EDITOR_FG: UInt8 = 0x02
let GUI_COLOR_TREE_BG: UInt8 = 0x03
let GUI_COLOR_TREE_FG: UInt8 = 0x04
let GUI_COLOR_TREE_SELECTION_BG: UInt8 = 0x05
let GUI_COLOR_TREE_DIR_FG: UInt8 = 0x06
let GUI_COLOR_TREE_ACTIVE_FG: UInt8 = 0x07
let GUI_COLOR_TREE_HEADER_BG: UInt8 = 0x08
let GUI_COLOR_TREE_HEADER_FG: UInt8 = 0x09
let GUI_COLOR_TREE_SEPARATOR_FG: UInt8 = 0x0A
let GUI_COLOR_TREE_GIT_MODIFIED: UInt8 = 0x0B
let GUI_COLOR_TREE_GIT_STAGED: UInt8 = 0x0C
let GUI_COLOR_TREE_GIT_UNTRACKED: UInt8 = 0x0D
let GUI_COLOR_TREE_SELECTION_FG: UInt8 = 0x0E
let GUI_COLOR_TREE_GUIDE_FG: UInt8 = 0x0F
let GUI_COLOR_TAB_BG: UInt8 = 0x10
let GUI_COLOR_TAB_ACTIVE_BG: UInt8 = 0x11
let GUI_COLOR_TAB_ACTIVE_FG: UInt8 = 0x12
let GUI_COLOR_TAB_INACTIVE_FG: UInt8 = 0x13
let GUI_COLOR_TAB_MODIFIED_FG: UInt8 = 0x14
let GUI_COLOR_TAB_SEPARATOR_FG: UInt8 = 0x15
let GUI_COLOR_TAB_CLOSE_HOVER_FG: UInt8 = 0x16
let GUI_COLOR_TAB_ATTENTION_FG: UInt8 = 0x17
let GUI_COLOR_POPUP_BG: UInt8 = 0x20
let GUI_COLOR_POPUP_FG: UInt8 = 0x21
let GUI_COLOR_POPUP_BORDER: UInt8 = 0x22
let GUI_COLOR_POPUP_SEL_BG: UInt8 = 0x23
let GUI_COLOR_POPUP_KEY_FG: UInt8 = 0x24
let GUI_COLOR_POPUP_GROUP_FG: UInt8 = 0x25
let GUI_COLOR_POPUP_DESC_FG: UInt8 = 0x26
let GUI_COLOR_BREADCRUMB_BG: UInt8 = 0x27
let GUI_COLOR_BREADCRUMB_FG: UInt8 = 0x28
let GUI_COLOR_BREADCRUMB_SEPARATOR_FG: UInt8 = 0x29
let GUI_COLOR_MODELINE_BAR_BG: UInt8 = 0x30
let GUI_COLOR_MODELINE_BAR_FG: UInt8 = 0x31
let GUI_COLOR_MODELINE_INFO_BG: UInt8 = 0x32
let GUI_COLOR_MODELINE_INFO_FG: UInt8 = 0x33
let GUI_COLOR_MODE_NORMAL_BG: UInt8 = 0x34
let GUI_COLOR_MODE_NORMAL_FG: UInt8 = 0x35
let GUI_COLOR_MODE_INSERT_BG: UInt8 = 0x36
let GUI_COLOR_MODE_INSERT_FG: UInt8 = 0x37
let GUI_COLOR_MODE_VISUAL_BG: UInt8 = 0x38
let GUI_COLOR_MODE_VISUAL_FG: UInt8 = 0x39
let GUI_COLOR_STATUSBAR_ACCENT_FG: UInt8 = 0x3A
let GUI_COLOR_ACCENT: UInt8 = 0x40

// Gutter + Git color slots
let GUI_COLOR_GUTTER_FG: UInt8 = 0x50
let GUI_COLOR_GUTTER_CURRENT_FG: UInt8 = 0x51
let GUI_COLOR_GUTTER_ERROR_FG: UInt8 = 0x52
let GUI_COLOR_GUTTER_WARNING_FG: UInt8 = 0x53
let GUI_COLOR_GUTTER_INFO_FG: UInt8 = 0x54
let GUI_COLOR_GUTTER_HINT_FG: UInt8 = 0x55
let GUI_COLOR_GUTTER_FOLD_FG: UInt8 = 0x62
let GUI_COLOR_GIT_ADDED_FG: UInt8 = 0x56
let GUI_COLOR_GIT_MODIFIED_FG: UInt8 = 0x57
let GUI_COLOR_GIT_DELETED_FG: UInt8 = 0x58
let GUI_COLOR_HIGHLIGHT_READ_BG: UInt8 = 0x59
let GUI_COLOR_HIGHLIGHT_WRITE_BG: UInt8 = 0x5A
let GUI_COLOR_SELECTION_BG: UInt8 = 0x5B

// Agent status color slots (shared across Board cards, tab bar badges, chat header, etc.)
let GUI_COLOR_AGENT_STATUS_IDLE: UInt8 = 0x5C
let GUI_COLOR_AGENT_STATUS_WORKING: UInt8 = 0x5D
let GUI_COLOR_AGENT_STATUS_ITERATING: UInt8 = 0x5E
let GUI_COLOR_AGENT_STATUS_NEEDS_YOU: UInt8 = 0x5F
let GUI_COLOR_AGENT_STATUS_DONE: UInt8 = 0x60
let GUI_COLOR_AGENT_STATUS_ERRORED: UInt8 = 0x61

// Agent chat theme color slots (populated from Theme.Agent on BEAM side)
let GUI_COLOR_AGENT_PANEL_BG: UInt8 = 0xA0
let GUI_COLOR_AGENT_HEADER_BG: UInt8 = 0xA1
let GUI_COLOR_AGENT_HEADER_FG: UInt8 = 0xA2
let GUI_COLOR_AGENT_USER_BORDER: UInt8 = 0xA3
let GUI_COLOR_AGENT_USER_LABEL: UInt8 = 0xA4
let GUI_COLOR_AGENT_ASSISTANT_BORDER: UInt8 = 0xA5
let GUI_COLOR_AGENT_ASSISTANT_LABEL: UInt8 = 0xA6
let GUI_COLOR_AGENT_INPUT_BORDER: UInt8 = 0xA7
let GUI_COLOR_AGENT_INPUT_BG: UInt8 = 0xA8
let GUI_COLOR_AGENT_INPUT_PLACEHOLDER: UInt8 = 0xA9
let GUI_COLOR_AGENT_TEXT_FG: UInt8 = 0xAA
let GUI_COLOR_AGENT_TOOL_BORDER: UInt8 = 0xAB
let GUI_COLOR_AGENT_TOOL_HEADER: UInt8 = 0xAC
let GUI_COLOR_AGENT_CODE_BG: UInt8 = 0xAD
let GUI_COLOR_AGENT_CODE_BORDER: UInt8 = 0xAE

// MARK: - Cursor shapes

let CURSOR_BLOCK: UInt8 = 0x00
let CURSOR_BEAM: UInt8 = 0x01
let CURSOR_UNDERLINE: UInt8 = 0x02

// MARK: - Capability constants

let CAPS_VERSION: UInt8 = 1

let FRONTEND_TUI: UInt8 = 0
let FRONTEND_NATIVE_GUI: UInt8 = 1

let COLOR_RGB: UInt8 = 2
let UNICODE_15: UInt8 = 1
let IMAGE_NATIVE: UInt8 = 3
let FLOAT_NATIVE: UInt8 = 1
let TEXT_PROPORTIONAL: UInt8 = 1

// MARK: - Text attribute bits

let ATTR_BOLD: UInt8 = 0x01
let ATTR_UNDERLINE: UInt8 = 0x02
let ATTR_ITALIC: UInt8 = 0x04
let ATTR_REVERSE: UInt8 = 0x08
let ATTR_STRIKETHROUGH: UInt16 = 0x10

// Underline style (3 bits at position 5-7 in extended 16-bit attrs)
let UL_STYLE_SHIFT: UInt16 = 5
let UL_STYLE_MASK: UInt16 = 0x07  // 3 bits
let UL_STYLE_LINE: UInt16 = 0
let UL_STYLE_CURL: UInt16 = 1
let UL_STYLE_DASHED: UInt16 = 2
let UL_STYLE_DOTTED: UInt16 = 3
let UL_STYLE_DOUBLE: UInt16 = 4

// Bold/italic style mask for font variant selection (bits 0 and 2 of attrs)
let FONT_STYLE_MASK: UInt8 = 0x05

// MARK: - Mouse button constants

let MOUSE_BUTTON_LEFT: UInt8 = 0x00
let MOUSE_BUTTON_MIDDLE: UInt8 = 0x01
let MOUSE_BUTTON_RIGHT: UInt8 = 0x02
let MOUSE_BUTTON_NONE: UInt8 = 0x03
let MOUSE_SCROLL_UP: UInt8 = 0x40
let MOUSE_SCROLL_DOWN: UInt8 = 0x41
let MOUSE_SCROLL_RIGHT: UInt8 = 0x42
let MOUSE_SCROLL_LEFT: UInt8 = 0x43

// MARK: - Settings value types

let SETTING_VALUE_BOOL: UInt8 = 0x01
let SETTING_VALUE_INT: UInt8 = 0x02
let SETTING_VALUE_STRING: UInt8 = 0x03
let SETTING_VALUE_ATOM: UInt8 = 0x04
let SETTING_VALUE_FLOAT: UInt8 = 0x05

// MARK: - Log levels (must match Zig protocol.zig and Elixir protocol.ex)

let LOG_LEVEL_ERR: UInt8 = 0
let LOG_LEVEL_WARN: UInt8 = 1
let LOG_LEVEL_INFO: UInt8 = 2
let LOG_LEVEL_DEBUG: UInt8 = 3

// MARK: - Mouse event types

let MOUSE_PRESS: UInt8 = 0x00
let MOUSE_RELEASE: UInt8 = 0x01
let MOUSE_MOTION: UInt8 = 0x02
let MOUSE_DRAG: UInt8 = 0x03
