defmodule Minga.Agent.Compaction do
  @moduledoc """
  Automatic context compaction for the native agent provider.

  When a conversation grows large enough to approach the model's context
  limit, this module summarizes older turns into a condensed message
  while preserving the system prompt and recent turns verbatim.

  The summary is generated by an LLM call using the same model, so it
  captures the salient points of the conversation without losing
  critical context like file paths, decisions made, and code snippets
  discussed.
  """

  alias Minga.Agent.ModelLimits
  alias Minga.Agent.TokenEstimator
  alias ReqLLM.Context
  alias ReqLLM.Message

  @typedoc "A function that takes (model, messages, opts) and returns {:ok, text} or {:error, reason}."
  @type summary_fn :: (String.t(), [Message.t()], keyword() ->
                         {:ok, String.t()} | {:error, term()})

  @typedoc "Options for compaction."
  @type compact_opts :: [
          model: String.t(),
          llm_client: summary_fn(),
          context_limit: pos_integer() | nil,
          threshold: float(),
          keep_recent: pos_integer()
        ]

  @default_threshold 0.80
  @default_keep_recent 6
  @default_context_limit 100_000
  @summary_max_tokens 2048

  @doc """
  Checks whether compaction is needed and performs it if so.

  Returns `{:compacted, new_context, summary_text}` if compaction was
  performed, or `{:ok, context}` if the context is within limits.

  Options:
  - `:model` — the model string (used for context limit lookup and summary call)
  - `:llm_client` — the LLM client function for generating the summary
  - `:context_limit` — override the model's context limit
  - `:threshold` — fraction of context limit that triggers compaction (default: 0.80)
  - `:keep_recent` — number of recent messages to preserve verbatim (default: 6)
  """
  @spec maybe_compact(Context.t(), compact_opts()) ::
          {:compacted, Context.t(), String.t()} | {:ok, Context.t()}
  def maybe_compact(context, opts) do
    estimated = TokenEstimator.estimate(context.messages)
    limit = resolve_context_limit(opts)
    threshold = Keyword.get(opts, :threshold, @default_threshold)

    if estimated > limit * threshold do
      compact(context, opts)
    else
      {:ok, context}
    end
  end

  @doc """
  Forces compaction regardless of token count.

  Useful for the `/compact` slash command.
  """
  @spec compact(Context.t(), compact_opts()) ::
          {:compacted, Context.t(), String.t()} | {:ok, Context.t()} | {:error, String.t()}
  def compact(context, opts) do
    messages = context.messages
    keep_recent = Keyword.get(opts, :keep_recent, @default_keep_recent)

    {system_msgs, conversation} = split_system(messages)

    # If the conversation is too short to compact, skip
    if length(conversation) <= keep_recent do
      {:ok, context}
    else
      {to_summarize, to_keep} = split_conversation(conversation, keep_recent)
      do_compact(system_msgs, to_summarize, to_keep, opts)
    end
  end

  # ── Private ─────────────────────────────────────────────────────────────────

  @spec do_compact([Message.t()], [Message.t()], [Message.t()], compact_opts()) ::
          {:compacted, Context.t(), String.t()} | {:error, String.t()}
  defp do_compact(system_msgs, to_summarize, to_keep, opts) do
    model = Keyword.fetch!(opts, :model)
    llm_client = Keyword.fetch!(opts, :llm_client)

    summary_prompt = build_summary_prompt(to_summarize)

    summary_messages = [
      Context.system(
        "You are a conversation summarizer. Produce a concise summary of the conversation below. " <>
          "Preserve: file paths, code snippets discussed, decisions made, tool results, and any " <>
          "pending tasks. Use bullet points. Be thorough but concise."
      ),
      Context.user(summary_prompt)
    ]

    case llm_client.(model, summary_messages, max_tokens: @summary_max_tokens) do
      {:ok, summary_text} when is_binary(summary_text) ->
        before_tokens = TokenEstimator.estimate(system_msgs ++ to_summarize ++ to_keep)

        summary_msg =
          Context.user(
            "[Conversation Summary — earlier context was compacted]\n\n#{summary_text}"
          )

        new_messages = system_msgs ++ [summary_msg] ++ to_keep
        after_tokens = TokenEstimator.estimate(new_messages)

        summary_info =
          "Context compacted (#{format_tokens(before_tokens)} → #{format_tokens(after_tokens)} estimated tokens)"

        {:compacted, Context.new(new_messages), summary_info}

      {:error, reason} ->
        {:error, "Compaction failed: #{inspect(reason)}"}
    end
  end

  @spec split_system([Message.t()]) :: {[Message.t()], [Message.t()]}
  defp split_system(messages) do
    Enum.split_while(messages, fn msg -> msg.role == :system end)
  end

  @spec split_conversation([Message.t()], pos_integer()) :: {[Message.t()], [Message.t()]}
  defp split_conversation(conversation, keep_recent) do
    total = length(conversation)
    split_at = max(0, total - keep_recent)
    Enum.split(conversation, split_at)
  end

  @spec build_summary_prompt([Message.t()]) :: String.t()
  defp build_summary_prompt(messages) do
    formatted =
      Enum.map_join(messages, "\n\n", fn msg ->
        role = msg.role |> Atom.to_string() |> String.capitalize()
        content = extract_content(msg)
        "**#{role}:**\n#{content}"
      end)

    "Summarize this conversation:\n\n#{formatted}"
  end

  @spec extract_content(Message.t()) :: String.t()
  defp extract_content(%{content: content}) when is_binary(content), do: content

  defp extract_content(%{content: parts}) when is_list(parts) do
    Enum.map_join(parts, "\n", fn
      %{text: text} -> text
      other -> inspect(other)
    end)
  end

  defp extract_content(_), do: ""

  @spec resolve_context_limit(compact_opts()) :: pos_integer()
  defp resolve_context_limit(opts) do
    case Keyword.get(opts, :context_limit) do
      nil ->
        model = Keyword.get(opts, :model, "")
        model_name = strip_provider_prefix(model)

        case ModelLimits.context_limit(model_name) do
          nil -> @default_context_limit
          limit -> limit
        end

      limit ->
        limit
    end
  end

  defdelegate strip_provider_prefix(model), to: Minga.Agent.Config

  @spec format_tokens(non_neg_integer()) :: String.t()
  defp format_tokens(tokens) when tokens >= 1000 do
    "#{Float.round(tokens / 1000, 1)}k"
  end

  defp format_tokens(tokens), do: "#{tokens}"
end
