/// Conformance transcript runner (#2667).
///
/// Executes the shared frontend conformance corpus (`test/conformance/corpus`)
/// against the macOS client's REAL protocol decoder, CommandDispatcher/store,
/// local-presentation reset decision, and pointer offset transform. The Go suite
/// executes the same corpus, so a divergence in store lifecycle or input
/// resolution fails a build instead of surfacing later as a rendering bug.
///
/// The corpus is generated by `mix conformance.gen` from the real BEAM encoder;
/// this runner never hand-builds wire bytes. It base64-decodes the fixtures and
/// feeds them through `decodeCommand` + `CommandDispatcher.applyForTesting`.

import MingaUI
import Testing
import Foundation
import AppKit
import CoreGraphics
import MingaProtocol

// MARK: - Corpus model

private enum ProductionCorpusStatus: String {
    case accepted
    case recoveryRequired = "recovery_required"
    case staleDiscarded = "stale_discarded"
    case unknown
}

struct ConformanceIndexEntry: Sendable, CustomTestStringConvertible {
    let name: String
    let category: String
    let file: String
    let swift: Bool
    let go: Bool

    var testDescription: String { name }
}

/// Transcripts the macOS suite runs (every transcript flagged `swift: true`).
let conformanceSwiftEntries: [ConformanceIndexEntry] = ConformanceTranscriptTests.loadIndex().filter { $0.swift }

@Suite("Frontend conformance transcripts")
struct ConformanceTranscriptTests {

    @Test("corpus enumerates transcripts")
    func corpusIsPopulated() {
        #expect(!conformanceSwiftEntries.isEmpty, "conformance corpus empty; run `mix conformance.gen`")
    }

    @Test("transcript conforms", arguments: conformanceSwiftEntries)
    @MainActor
    func runsTranscript(_ entry: ConformanceIndexEntry) throws {
        let steps = try Self.loadSteps(entry.file)
        let gui = GUIState()
        let dispatcher = CommandDispatcher(cols: 80, rows: 24, guiState: gui)

        var frameReset = false
        dispatcher.onScrollPresentationReset = { frameReset = true }

        // Per-window injected local offset (state injection: the point of the
        // input suite is running a transcript against a nonzero local offset).
        var injectedRowOffset: [UInt16: Int] = [:]
        var injectedColOffset: [UInt16: Int] = [:]

        for (i, step) in steps.enumerated() {
            let kind = step["kind"] as? String ?? ""
            switch kind {
            case "frame":
                frameReset = false
                let commands = try Self.decodeFrame(step, index: i, name: entry.name)
                for command in commands { dispatcher.applyForTesting(command) }
                if let expect = step["expect"] as? [String: Any] {
                    let windowId = commands.compactMap(Self.windowId(of:)).first ?? 1
                    Self.assertFrame(expect, gui: gui, windowId: windowId,
                                     offsetDiscarded: frameReset, index: i, name: entry.name)
                }

            case "production_fixture":
                try Self.assertProductionFixture(
                    step, index: i, name: entry.name, dispatcher: dispatcher, gui: gui
                )

            case "inject_offset":
                let windowId = UInt16(step["window_id"] as? Int ?? 1)
                injectedRowOffset[windowId] = step["row_offset"] as? Int ?? 0
                injectedColOffset[windowId] = step["col_offset"] as? Int ?? 0

            case "pointer":
                let windowId = UInt16(step["window_id"] as? Int ?? 1)
                Self.assertPointer(step, gui: gui, windowId: windowId,
                                   rowOffset: injectedRowOffset[windowId] ?? 0,
                                   colOffset: injectedColOffset[windowId] ?? 0,
                                   index: i, name: entry.name)

            case "transcript_frame":
                let commands = try Self.decodeFrame(step, index: i, name: entry.name)
                for command in commands { dispatcher.applyForTesting(command) }
                if let expect = step["expect"] as? [String: Any],
                   let transcript = expect["transcript"] as? [String: Any] {
                    Self.assertTranscript(transcript, state: gui.agentChatState, index: i, name: entry.name)
                }

            case "transcript_scroll":
                // Local scroll is a SwiftUI view concern (ScrollView offset), not a
                // store mutation: the macOS store is unaffected. Position preservation
                // is asserted via id stability on transcript_assert steps instead.
                break

            case "transcript_assert":
                if let swift = step["swift"] as? [String: Any] {
                    Self.assertTranscriptAnchor(swift, state: gui.agentChatState, index: i, name: entry.name)
                }

            default:
                Issue.record("\(entry.name) step \(i): unknown kind \(kind)")
            }
        }
    }

    // MARK: - Frame assertions

    @MainActor
    static func assertFrame(_ expect: [String: Any], gui: GUIState, windowId: UInt16,
                            offsetDiscarded: Bool, index: Int, name: String) {
        let window = gui.windowContents[windowId]

        if let wantPresent = expect["store_present"] as? Bool {
            #expect((window != nil) == wantPresent,
                    "\(name) step \(index): store_present = \(window != nil), want \(wantPresent)")
        }

        if let wantRows = expect["rows"] as? [[String: Any]] {
            assertRows(wantRows, rows: window?.rows ?? [], index: index, name: name)
        }

        if let wantAnchor = expect["anchor"] as? [String: Any], let sp = window?.scrollPresentation {
            let top = wantAnchor["top"] as? Int ?? -1
            let left = wantAnchor["left"] as? Int ?? -1
            #expect(Int(sp.anchorTop) == top && Int(sp.anchorLeft) == left,
                    "\(name) step \(index): anchor = {top:\(sp.anchorTop) left:\(sp.anchorLeft)}, want {top:\(top) left:\(left)}")
        }

        if let wantCursor = expect["cursor_row"] as? Int, let window {
            #expect(Int(window.cursorRow) == wantCursor,
                    "\(name) step \(index): cursor_row = \(window.cursorRow), want \(wantCursor)")
        }

        if let wantDiscarded = expect["offset_discarded"] as? Bool {
            #expect(offsetDiscarded == wantDiscarded,
                    "\(name) step \(index): offset_discarded = \(offsetDiscarded), want \(wantDiscarded)")
        }
    }

    static func assertRows(_ want: [[String: Any]], rows: [GUIVisualRow], index: Int, name: String) {
        guard rows.count == want.count else {
            Issue.record("\(name) step \(index): resident row count = \(rows.count), want \(want.count)")
            return
        }
        for (j, wantRow) in want.enumerated() {
            let wantId = UInt64(wantRow["row_id"] as? String ?? "") ?? 0
            let wantHash = UInt32(wantRow["content_hash"] as? Int ?? 0)
            let wantLine = UInt32(wantRow["buf_line"] as? Int ?? 0)
            let row = rows[j]
            #expect(row.rowId == wantId && row.contentHash == wantHash && row.bufLine == wantLine,
                    "\(name) step \(index): row \(j) = {id:\(row.rowId) hash:\(row.contentHash) line:\(row.bufLine)}, want {id:\(wantId) hash:\(wantHash) line:\(wantLine)}")
        }
    }

    // MARK: - Resident agent-transcript assertions (0x86, #2654)

    /// Asserts the resident store's epoch, truncated flag, count, and ordered
    /// message ids after a 0x86 frame. This is the shared parity assertion the Go
    /// runner mirrors: both decode the same encoder bytes through their real store
    /// apply (`AgentChatState.applyTranscript`) and must produce the same id list.
    @MainActor
    static func assertTranscript(_ expect: [String: Any], state: AgentChatState, index: Int, name: String) {
        if let wantEpoch = expect["epoch"] as? Int {
            #expect(Int(state.transcriptEpoch) == wantEpoch,
                    "\(name) step \(index): epoch = \(state.transcriptEpoch), want \(wantEpoch)")
        }
        if let wantTruncated = expect["truncated"] as? Bool {
            #expect(state.transcriptTruncated == wantTruncated,
                    "\(name) step \(index): truncated = \(state.transcriptTruncated), want \(wantTruncated)")
        }
        if let wantIds = expect["message_ids"] as? [Int] {
            let gotIds = state.messages.map { $0.id }
            #expect(gotIds == wantIds,
                    "\(name) step \(index): resident ids = \(gotIds), want \(wantIds)")
        }
        if let wantCount = expect["count"] as? Int {
            #expect(state.messages.count == wantCount,
                    "\(name) step \(index): resident count = \(state.messages.count), want \(wantCount)")
        }
    }

    /// Asserts the message at a store index still carries the expected id (the
    /// SwiftUI-native position-preservation check: `ForEach(id:)` stability is what
    /// keeps the reader's scroll position across an append, so a stable anchor id
    /// at a stable index is the store-side proof).
    @MainActor
    static func assertTranscriptAnchor(_ swift: [String: Any], state: AgentChatState, index: Int, name: String) {
        guard let anchorIndex = swift["anchor_index"] as? Int,
              let anchorId = swift["anchor_id"] as? Int else { return }
        guard anchorIndex < state.messages.count else {
            Issue.record("\(name) step \(index): anchor_index \(anchorIndex) out of range (\(state.messages.count) messages)")
            return
        }
        let gotId = state.messages[anchorIndex].id
        #expect(gotId == anchorId,
                "\(name) step \(index): id at store index \(anchorIndex) = \(gotId), want \(anchorId)")
    }

    // MARK: - Compact production fixture

    @MainActor
    static func assertProductionFixture(
        _ step: [String: Any], index: Int, name: String,
        dispatcher: CommandDispatcher, gui: GUIState
    ) throws {
        guard let fixture = step["fixture"] as? [String: Any],
              let operations = step["operations"] as? [[String: Any]] else {
            throw ConformanceError.badTranscript("\(name) step \(index)")
        }
        let rowCount = fixture["row_count"] as? Int ?? 0
        let wideTextBytes = fixture["wide_text_bytes"] as? Int ?? 0
        let editIndex = fixture["ordinary_edit_index"] as? Int ?? 0
        let structuralIndex = fixture["structural_edit_index"] as? Int ?? 0
        let prefix = fixture["row_text_prefix"] as? String ?? "row-"
        #expect(rowCount == 65_536)
        #expect(wideTextBytes > UInt16.max)

        let wideText = String(repeating: "w", count: wideTextBytes)
        var rows = (0..<rowCount).map { row in
            let text = row == 0 ? wideText : prefix + String(row)
            return GUIVisualRow(
                rowType: .normal, rowId: UInt64(row + 1), bufLine: UInt32(row),
                contentHash: UInt32(row + 1), text: text, spans: []
            )
        }
        #expect(rows[0].text.utf8.count == wideTextBytes)
        let originalRows = rows

        var store = try ResidentRowStore(rows: rows)
        #expect(store.count == rowCount)
        #expect(store.counters.fullResets == expectedCount("keyframe", "full_resets", operations))

        var before = store.counters
        rows[editIndex] = GUIVisualRow(
            rowType: .normal, rowId: rows[editIndex].rowId, bufLine: UInt32(editIndex),
            contentHash: rows[editIndex].contentHash &+ 1, text: "edited", spans: [])
        try store.replace(at: editIndex, with: rows[editIndex])
        var delta = store.counters - before
        #expect(delta.fullResets == expectedCount("ordinary_edit", "full_resets", operations))
        #expect(delta.splices == expectedCount("ordinary_edit", "splices", operations))
        #expect(delta.changedRowsValidated == expectedCount("ordinary_edit", "changed_rows", operations))
        #expect(delta.chunksTouched <= 4)

        before = store.counters
        let inserted = GUIVisualRow(rowType: .normal, rowId: UInt64.max - 1,
                                    bufLine: UInt32(structuralIndex), contentHash: 0xA11CE,
                                    text: "inserted-near-start", spans: [])
        try store.splice(at: structuralIndex, removeCount: 0, inserting: [inserted])
        delta = store.counters - before
        #expect(delta.fullResets == expectedCount("structural_edit_near_start", "full_resets", operations))
        #expect(delta.splices == expectedCount("structural_edit_near_start", "splices", operations))
        #expect(delta.changedRowsValidated == expectedCount("structural_edit_near_start", "changed_rows", operations))

        before = store.counters
        _ = try store.resolve(rowID: rows[editIndex].rowId, contentHash: rows[editIndex].contentHash)
        delta = store.counters - before
        #expect(delta.idsResolved == expectedCount("retained_reference", "ids_resolved", operations))

        let epoch = UInt32(fixture["content_epoch"] as? Int ?? 0)
        let staleEpoch = UInt32(fixture["stale_content_epoch"] as? Int ?? 0)
        let generation = UInt32(fixture["recovery_generation"] as? Int ?? 0)
        let staleGeneration = UInt32(fixture["stale_recovery_generation"] as? Int ?? 0)
        var results: [FrameTransactionResult] = []
        dispatcher.onTransactionResult = { results.append($0) }
        let theme = CommandDispatcher.requiredThemeSlots.map { ($0, $0, $0, $0) }
        let paneGeometry = productionPaneGeometry(rowCount: rowCount)
        let epochContent = try GUIWindowContent(
            windowId: 1, fullRefresh: true, contentEpoch: epoch,
            cursorRow: 0, cursorCol: 0, cursorShape: .block, rows: originalRows,
            selection: nil, searchMatches: [], diagnosticUnderlines: [], documentHighlights: [],
            paneGeometry: paneGeometry
        )
        dispatcher.dispatch(.beginFrame(frameSeq: 1, baseFrameSeq: 0, generation: generation))
        dispatcher.dispatch(.guiTheme(slots: theme))
        dispatcher.dispatch(.guiWindowContent(data: epochContent))
        dispatcher.dispatch(.commitFrame(frameSeq: 1, seq: 0))
        let keyframePublication = dispatcher.publicationCount

        let ordinaryDelta = GUIWindowRowsDelta(
            windowId: 1, contentEpoch: epoch, cursorVisible: true,
            cursorRow: 0, cursorCol: 0, cursorShape: .block, scrollLeft: 0,
            baseRowCount: UInt32(rowCount), resultRowCount: UInt32(rowCount),
            rowSplices: [GUIWindowRowSplice(startIndex: UInt32(editIndex), deleteCount: 1,
                                            insertEntries: [.full(rows[editIndex])])],
            selection: nil, searchMatches: [], diagnosticUnderlines: [], documentHighlights: [],
            lineAnnotations: [], paneGeometry: nil, cursorline: nil
        )
        dispatcher.dispatch(.beginFrame(frameSeq: 2, baseFrameSeq: 1, generation: generation))
        dispatcher.dispatch(.guiWindowRowsDelta(data: ordinaryDelta))
        dispatcher.dispatch(.commitFrame(frameSeq: 2, seq: 0))

        let structuralDelta = GUIWindowRowsDelta(
            windowId: 1, contentEpoch: epoch, cursorVisible: true,
            cursorRow: 0, cursorCol: 0, cursorShape: .block, scrollLeft: 0,
            baseRowCount: UInt32(rowCount), resultRowCount: UInt32(rowCount + 1),
            rowSplices: [GUIWindowRowSplice(startIndex: UInt32(structuralIndex), deleteCount: 0,
                                            insertEntries: [.full(inserted)])],
            selection: nil, searchMatches: [], diagnosticUnderlines: [], documentHighlights: [],
            lineAnnotations: [], paneGeometry: nil, cursorline: nil
        )
        dispatcher.dispatch(.beginFrame(frameSeq: 3, baseFrameSeq: 2, generation: generation))
        dispatcher.dispatch(.guiWindowRowsDelta(data: structuralDelta))
        dispatcher.dispatch(.commitFrame(frameSeq: 3, seq: 0))

        let retainedIndex = editIndex + 1
        let retainedDelta = GUIWindowRowsDelta(
            windowId: 1, contentEpoch: epoch, cursorVisible: true,
            cursorRow: 0, cursorCol: 0, cursorShape: .block, scrollLeft: 0,
            baseRowCount: UInt32(rowCount + 1), resultRowCount: UInt32(rowCount + 1),
            rowSplices: [GUIWindowRowSplice(startIndex: UInt32(retainedIndex), deleteCount: 1,
                insertEntries: [.reference(rowId: rows[editIndex].rowId,
                                           contentHash: rows[editIndex].contentHash)])],
            selection: nil, searchMatches: [], diagnosticUnderlines: [], documentHighlights: [],
            lineAnnotations: [], paneGeometry: nil, cursorline: nil
        )
        dispatcher.dispatch(.beginFrame(frameSeq: 4, baseFrameSeq: 3, generation: generation))
        dispatcher.dispatch(.guiWindowRowsDelta(data: retainedDelta))
        dispatcher.dispatch(.commitFrame(frameSeq: 4, seq: 0))
        #expect(gui.windowContents[1]?.rowStore.count == rowCount + 1)
        let committedPublication = dispatcher.publicationCount
        #expect(committedPublication == keyframePublication + 3)

        let missing = GUIWindowRowsDelta(
            windowId: 1, contentEpoch: epoch, cursorVisible: true,
            cursorRow: 0, cursorCol: 0, cursorShape: .block, scrollLeft: 0,
            rows: [.reference(rowId: UInt64.max, contentHash: 1)],
            selection: nil, searchMatches: [], diagnosticUnderlines: [], documentHighlights: [],
            lineAnnotations: [], paneGeometry: nil, cursorline: nil
        )
        dispatcher.dispatch(.beginFrame(frameSeq: 5, baseFrameSeq: 4, generation: generation))
        dispatcher.dispatch(.guiWindowRowsDelta(data: missing))
        dispatcher.dispatch(.commitFrame(frameSeq: 5, seq: 0))
        let referenceMissStatus = results.last.map(Self.productionStatus) ?? .unknown

        let staleOverlay = GUIWindowOverlayDelta(
            windowId: 1, contentEpoch: staleEpoch, cursorVisible: true,
            cursorRow: 0, cursorCol: 0, cursorShape: .block, cursorline: nil
        )
        dispatcher.dispatch(.beginFrame(frameSeq: 6, baseFrameSeq: 4, generation: generation))
        dispatcher.dispatch(.guiWindowOverlayDelta(data: staleOverlay))
        dispatcher.dispatch(.commitFrame(frameSeq: 6, seq: 0))
        let staleEpochStatus: ProductionCorpusStatus =
            dispatcher.publicationCount == committedPublication ? .staleDiscarded : .accepted

        dispatcher.dispatch(.beginFrame(frameSeq: 7, baseFrameSeq: 4, generation: staleGeneration))
        dispatcher.dispatch(.guiWindowContent(data: try GUIWindowContent(
            windowId: 1, fullRefresh: true, contentEpoch: epoch,
            cursorRow: 0, cursorCol: 0, cursorShape: .block,
            rows: [GUIVisualRow(rowType: .normal, rowId: 999, bufLine: 0,
                                contentHash: 999, text: "must-not-publish", spans: [])],
            selection: nil, searchMatches: [], diagnosticUnderlines: [], documentHighlights: [],
            paneGeometry: paneGeometry
        )))
        dispatcher.dispatch(.commitFrame(frameSeq: 7, seq: 0))
        let staleGenerationStatus: ProductionCorpusStatus =
            dispatcher.publicationCount == committedPublication
                && dispatcher.lastCommittedGeneration == generation ? .staleDiscarded : .accepted

        #expect(expectedStatus("reference_miss", operations) == referenceMissStatus)
        #expect(expectedStatus("stale_content_epoch", operations) == staleEpochStatus)
        #expect(expectedStatus("stale_recovery_generation", operations) == staleGenerationStatus)

        before = store.counters
        try store.replaceAll(with: rows)
        delta = store.counters - before
        #expect(delta.fullResets == expectedCount("reset_full_recovery", "full_resets", operations))
        #expect(store.count == rowCount)

        dispatcher.dispatch(.beginFrame(frameSeq: 8, baseFrameSeq: 0, generation: generation))
        dispatcher.dispatch(.guiTheme(slots: theme))
        dispatcher.dispatch(.guiWindowContent(data: epochContent))
        dispatcher.dispatch(.commitFrame(frameSeq: 8, seq: 0))
        #expect(gui.windowContents[1]?.rowStore.count == rowCount)
    }

    static func expectedCount(_ operation: String, _ field: String,
                              _ operations: [[String: Any]]) -> Int {
        operations.first { $0["name"] as? String == operation }?[field] as? Int ?? 0
    }

    private static func productionPaneGeometry(rowCount: Int) -> GUIPaneGeometry {
        GUIPaneGeometry(
            windowId: 1,
            totalRect: GUICellRect(row: 0, col: 0, width: 80, height: 24),
            contentRect: GUICellRect(row: 0, col: 0, width: 80, height: 24),
            textRect: GUICellRect(row: 0, col: 0, width: 80, height: 24),
            gutterRect: GUICellRect(row: 0, col: 0, width: 0, height: 24),
            clipRect: GUICellRect(row: 0, col: 0, width: 80, height: 24),
            viewport: GUIViewportSummary(top: 0, left: 0, rows: 24, cols: 80, totalLines: UInt32(rowCount), visualRowOffset: 0, totalVisualRows: UInt32(rowCount)),
            gutterMetrics: GUIGutterMetrics(lineNumberWidth: 0, signColWidth: 0),
            hitRegions: []
        )
    }

    private static func productionStatus(_ result: FrameTransactionResult) -> ProductionCorpusStatus {
        switch result {
        case .applied: .accepted
        case .windowRefMiss: .recoveryRequired
        case .rejected: .staleDiscarded
        }
    }

    private static func expectedStatus(
        _ operation: String, _ operations: [[String: Any]]
    ) -> ProductionCorpusStatus {
        let raw = operations.first { $0["name"] as? String == operation }?["expect_status"] as? String
        return raw.flatMap(ProductionCorpusStatus.init(rawValue:)) ?? .unknown
    }

    // MARK: - Pointer normalization

    @MainActor
    static func assertPointer(_ step: [String: Any], gui: GUIState, windowId: UInt16,
                              rowOffset: Int, colOffset: Int, index: Int, name: String) {
        guard let window = gui.windowContents[windowId],
              let rect = window.paneGeometry?.contentRect,
              let sp = window.scrollPresentation else {
            Issue.record("\(name) step \(index): pointer step needs a stored window with geometry and scroll")
            return
        }
        let pointerRow = step["pointer_row"] as? Int ?? 0
        let pointerCol = step["pointer_col"] as? Int ?? 0

        // Real offset transform (mirrors EditorNSView.presentationNormalizedPoint
        // with cellHeight = 1 so pixel space == row space): add the presentation
        // offset, then clamp to the window content rect.
        let offset = EditorNSView.presentationScrollOffset(
            scrollLeft: 0, scrollOffset: CGPoint(x: CGFloat(colOffset), y: CGFloat(rowOffset)))
        let raw = NSPoint(x: CGFloat(pointerCol), y: CGFloat(pointerRow))
        let normalized = NSPoint(x: raw.x + offset.x, y: raw.y + offset.y)
        let clamped = EditorNSView.clampPresentationPoint(normalized, to: rect, cellWidth: 1, cellHeight: 1)
        let normalizedRow = Int(clamped.y.rounded(.down))
        let bufferLine = Int(sp.anchorTop) + normalizedRow

        if let expect = step["expect"] as? [String: Any], let want = expect["normalized_buffer_line"] as? Int {
            #expect(bufferLine == want,
                    "\(name) step \(index): normalized_buffer_line = \(bufferLine), want \(want)")
        }
    }

    // MARK: - Decoding

    static func decodeFrame(_ step: [String: Any], index: Int, name: String) throws -> [RenderCommand] {
        guard let b64 = step["payload_base64"] as? String, let payload = Data(base64Encoded: b64) else {
            throw ConformanceError.badPayload("\(name) step \(index)")
        }
        var commands: [RenderCommand] = []
        var offset = 0
        while offset < payload.count {
            let (command, size) = try decodeCommand(data: payload, offset: offset)
            if let command { commands.append(command) }
            if size <= 0 { break }
            offset += size
        }
        return commands
    }

    static func windowId(of command: RenderCommand) -> UInt16? {
        switch command {
        case .guiWindowContent(let data): return data.windowId
        case .guiWindowOverlayDelta(let delta): return delta.windowId
        case .guiWindowViewportDelta(let delta): return delta.windowId
        case .guiWindowRowsDelta(let delta): return delta.windowId
        default: return nil
        }
    }

    // MARK: - Corpus loading

    static func corpusURL() -> URL {
        URL(fileURLWithPath: #filePath)          // .../macos/Tests/MingaTests/ConformanceTranscriptTests.swift
            .deletingLastPathComponent()          // MingaTests
            .deletingLastPathComponent()          // Tests
            .deletingLastPathComponent()          // macos
            .deletingLastPathComponent()          // repo root
            .appendingPathComponent("test/conformance/corpus")
    }

    static func loadIndex() -> [ConformanceIndexEntry] {
        let url = corpusURL().appendingPathComponent("index.json")
        guard let data = try? Data(contentsOf: url),
              let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let list = root["transcripts"] as? [[String: Any]] else {
            return []
        }
        return list.map { entry in
            ConformanceIndexEntry(
                name: entry["name"] as? String ?? "",
                category: entry["category"] as? String ?? "",
                file: entry["file"] as? String ?? "",
                swift: entry["swift"] as? Bool ?? true,
                go: entry["go"] as? Bool ?? true)
        }
    }

    static func loadSteps(_ file: String) throws -> [[String: Any]] {
        let url = corpusURL().appendingPathComponent(file)
        let data = try Data(contentsOf: url)
        guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let steps = root["steps"] as? [[String: Any]] else {
            throw ConformanceError.badTranscript(file)
        }
        return steps
    }
}

enum ConformanceError: Error {
    case badPayload(String)
    case badTranscript(String)
}
