defmodule Minga.RenderModel.UI do
  @moduledoc false

  @type t :: %__MODULE__{
          theme: term(),
          breadcrumb: term(),
          which_key: term(),
          notifications: term(),
          search_state: term(),
          git_status: term(),
          agent_context: term(),
          status_bar: term(),
          observatory: Minga.RenderModel.UI.Observatory.t() | nil,
          tab_bar: term(),
          workspaces: term(),
          sidebars: term(),
          file_tree: term(),
          picker: term(),
          minibuffer: term(),
          completion: Minga.RenderModel.UI.Completion.t() | nil,
          signature_help: Minga.RenderModel.UI.SignatureHelp.t() | nil,
          agent_chat: term(),
          empty_state: Minga.RenderModel.UI.EmptyState.t() | nil,
          bottom_panel: term(),
          edit_timeline: term(),
          extension_overlay: Minga.RenderModel.UI.ExtensionOverlay.t() | nil,
          extension_panel: Minga.RenderModel.UI.ExtensionPanel.t() | nil,
          hover_popup: Minga.RenderModel.UI.HoverPopup.t() | nil,
          float_popup: Minga.RenderModel.UI.FloatPopup.t() | nil,
          gutter_separator: term(),
          split_separators: term(),
          line_spacing: Minga.RenderModel.UI.LineSpacing.t() | nil,
          cursor_animation: Minga.RenderModel.UI.CursorAnimation.t() | nil,
          config_state: Minga.RenderModel.UI.ConfigState.t() | nil
        }

  defstruct [
    :theme,
    :breadcrumb,
    :which_key,
    :notifications,
    :search_state,
    :git_status,
    :agent_context,
    :status_bar,
    :observatory,
    :tab_bar,
    :workspaces,
    :sidebars,
    :file_tree,
    :picker,
    :minibuffer,
    :completion,
    :signature_help,
    :agent_chat,
    :empty_state,
    :bottom_panel,
    :edit_timeline,
    :extension_overlay,
    :extension_panel,
    :hover_popup,
    :float_popup,
    :gutter_separator,
    :split_separators,
    :line_spacing,
    :cursor_animation,
    :config_state
  ]
end
