# This module changes the working directory to exercise a Mix task that resolves repo-local paths.
defmodule Mix.Tasks.LanguageAliases.GenTest do
  # Changes the process working directory while exercising the repo-local Mix task.
  use ExUnit.Case, async: false

  @source_path "config/language_aliases.json"
  @generated_elixir_path ".generated/language_aliases/elixir/lib/minga/language/generated_aliases.ex"
  @generated_zig_path "zig/src/generated/language_aliases.zig"

  test "generates Elixir and Zig language alias artifacts from the source file" do
    with_fixture_dir(fn dir ->
      File.cd!(dir, fn ->
        assert :ok = Mix.Tasks.LanguageAliases.Gen.run([])
      end)

      elixir = File.read!(Path.join(dir, @generated_elixir_path))
      zig = File.read!(Path.join(dir, @generated_zig_path))

      assert elixir =~ "Code generated by mix language_aliases.gen"
      assert elixir =~ ~s("js" => "javascript")
      assert elixir =~ ~s("c++" => "cpp")

      assert zig =~ "Generated from `config/language_aliases.json`"
      assert zig =~ ~s(.{ .from = "js", .to = "javascript" },)
      assert zig =~ ~s("javascript",)
    end)
  end

  test "--check passes against generated artifacts" do
    with_fixture_dir(fn dir ->
      File.cd!(dir, fn ->
        assert :ok = Mix.Tasks.LanguageAliases.Gen.run([])
        assert :ok = Mix.Tasks.LanguageAliases.Gen.run(["--check"])
      end)
    end)
  end

  test "--check fails when generated artifacts drift" do
    with_fixture_dir(fn dir ->
      File.cd!(dir, fn ->
        assert :ok = Mix.Tasks.LanguageAliases.Gen.run([])
      end)

      Path.join(dir, @generated_zig_path)
      |> File.write!("pub const aliases = .{};\n")

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Generated language alias artifacts are out of date/, fn ->
          Mix.Tasks.LanguageAliases.Gen.run(["--check"])
        end
      end)
    end)
  end

  test "rejects duplicate aliases in the source file" do
    with_fixture_dir(fn dir ->
      write_source!(dir, [
        %{"from" => "js", "to" => "javascript"},
        %{"from" => "js", "to" => "javascript"}
      ])

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Duplicate language alias "js"/, fn ->
          Mix.Tasks.LanguageAliases.Gen.run([])
        end
      end)
    end)
  end

  @spec with_fixture_dir((Path.t() -> any())) :: any()
  defp with_fixture_dir(fun) do
    dir =
      Path.join(System.tmp_dir!(), "language-aliases-gen-#{System.unique_integer([:positive])}")

    File.rm_rf!(dir)
    File.mkdir_p!(dir)

    write_source!(dir, [
      %{"from" => "js", "to" => "javascript"},
      %{"from" => "c++", "to" => "cpp"}
    ])

    try do
      fun.(dir)
    after
      File.rm_rf!(dir)
    end
  end

  @spec write_source!(Path.t(), [map()]) :: :ok
  defp write_source!(dir, aliases) do
    path = Path.join(dir, @source_path)
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, JSON.encode!(%{"aliases" => aliases}))
  end
end
