# This module changes the working directory to exercise a Mix task that resolves repo-local paths.
defmodule Mix.Tasks.Protocol.GenTest do
  # Changes the process working directory while exercising the repo-local Mix task.
  use ExUnit.Case, async: false

  @repo_root File.cwd!()
  @fixture_paths [
    "docs/protocol_schema.toml",
    "zig/src/protocol.zig"
  ]
  @generated_paths [
    ".generated/protocol/elixir/lib/minga/protocol/opcodes.ex",
    "macos/.generated/protocol/ProtocolOpcodes.generated.swift",
    "zig/src/generated/protocol_opcodes.zig",
    "zig/src/generated/protocol_schema_test.zig"
  ]

  test "generates protocol artifacts into ignored build locations" do
    with_fixture_dir(fn dir ->
      File.cd!(dir, fn ->
        assert :ok = generate_fast([])
      end)

      for rel_path <- @generated_paths do
        path = Path.join(dir, rel_path)
        assert File.exists?(path), "expected #{rel_path} to be generated"
        assert File.read!(path) =~ "Generated from `docs/protocol_schema.toml`"
      end
    end)
  end

  @tag :heavy
  test "Mix task formats generated Go artifacts" do
    with_fixture_dir(fn dir ->
      File.cd!(dir, fn ->
        assert :ok = Mix.Tasks.Protocol.Gen.run([])
      end)

      generated_go = Path.join(dir, "go/tui/internal/generated/opcodes.go")
      assert File.exists?(generated_go)
      assert File.read!(generated_go) =~ "Code generated by mix protocol.gen"
    end)
  end

  test "--check passes against generated artifacts" do
    with_fixture_dir(fn dir ->
      File.cd!(dir, fn ->
        assert :ok = generate_fast([])
        assert :ok = generate_fast(["--check"])
      end)
    end)
  end

  test "--check fails when a generated artifact drifts" do
    with_fixture_dir(fn dir ->
      File.cd!(dir, fn ->
        assert :ok = generate_fast([])
      end)

      Path.join([dir, "macos/.generated/protocol/ProtocolOpcodes.generated.swift"])
      |> File.write!("let OP_KEY_PRESS: UInt8 = 0x02\n")

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Generated protocol artifacts are out of date/, fn ->
          generate_fast(["--check"])
        end
      end)
    end)
  end

  test "--check fails when generated artifacts are missing" do
    with_fixture_dir(fn dir ->
      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Run `mix protocol.gen`/, fn ->
          generate_fast(["--check"])
        end
      end)
    end)
  end

  test "generates Zig protocol public exports from the schema" do
    with_fixture_dir(fn dir ->
      mutate_schema(dir, fn schema ->
        String.replace(
          schema,
          "[[opcodes]]\ncategory = \"input\"\nname = \"log_message\"\nvalue = 0x60\ndirection = \"frontend_to_beam\"",
          "[[opcodes]]\ncategory = \"input\"\nname = \"log_message\"\nvalue = 0x60\ndirection = \"frontend_to_beam\"\n\n[[opcodes]]\ncategory = \"input\"\nname = \"test_sync\"\n# Test-only sentinel: keep far from allocatable slots (0x08 collided with request_keyframe).\nvalue = 0x6E\ndirection = \"frontend_to_beam\"",
          global: false
        )
      end)

      File.cd!(dir, fn ->
        assert :ok = generate_fast([])

        assert File.read!("zig/src/protocol.zig") =~
                 "pub const OP_TEST_SYNC = opcodes.OP_TEST_SYNC;"

        assert File.read!("zig/src/generated/protocol_schema_test.zig") =~ "protocol.OP_TEST_SYNC"
        assert :ok = generate_fast(["--check"])
      end)
    end)
  end

  test "--check fails when Zig protocol public exports drift" do
    with_fixture_dir(fn dir ->
      File.cd!(dir, fn ->
        assert :ok = generate_fast([])
      end)

      path = Path.join(dir, "zig/src/protocol.zig")

      stale =
        String.replace(File.read!(path), "pub const OP_READY = opcodes.OP_READY;", "",
          global: false
        )

      File.write!(path, stale)

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Generated Zig protocol opcode exports are out of date/, fn ->
          generate_fast(["--check"])
        end
      end)
    end)
  end

  test "rejects duplicate opcode values" do
    with_fixture_dir(fn dir ->
      mutate_schema(dir, fn schema ->
        String.replace(
          schema,
          "name = \"resize\"\nvalue = 0x02",
          "name = \"resize\"\nvalue = 0x01",
          global: false
        )
      end)

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Duplicate opcode values/, fn ->
          generate_fast([])
        end
      end)
    end)
  end

  test "rejects duplicate gui action values" do
    with_fixture_dir(fn dir ->
      mutate_schema(dir, fn schema ->
        String.replace(
          schema,
          "name = \"git_open_diff\"\nvalue = 0x42",
          "name = \"git_open_diff\"\nvalue = 0x1E",
          global: false
        )
      end)

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Duplicate GUI action values/, fn ->
          generate_fast([])
        end
      end)
    end)
  end

  test "rejects invalid opcode categories" do
    with_fixture_dir(fn dir ->
      mutate_schema(dir, fn schema ->
        String.replace(schema, "category = \"render\"", "category = \"rendering\"", global: false)
      end)

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Invalid opcode categories/, fn ->
          generate_fast([])
        end
      end)
    end)
  end

  test "rejects invalid opcode directions" do
    with_fixture_dir(fn dir ->
      mutate_schema(dir, fn schema ->
        String.replace(schema, "direction = \"beam_to_frontend\"", "direction = \"sideways\"",
          global: false
        )
      end)

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Invalid opcode directions/, fn ->
          generate_fast([])
        end
      end)
    end)
  end

  test "rejects invalid gui_action canonical references" do
    with_fixture_dir(fn dir ->
      mutate_schema(dir, fn schema ->
        String.replace(schema, "canonical = \"git_commit\"", "canonical = \"missing_action\"",
          global: false
        )
      end)

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/Invalid gui_action canonical references/, fn ->
          generate_fast([])
        end
      end)
    end)
  end

  test "rejects optional on a command_fields field" do
    with_fixture_dir(fn dir ->
      mutate_schema(dir, fn schema ->
        String.replace(
          schema,
          "{ name = \"color_count\", type = \"u8\" }",
          "{ name = \"color_count\", type = \"u8\", optional = true }",
          global: false
        )
      end)

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/only allowed on section fields/, fn ->
          generate_fast([])
        end
      end)
    end)
  end

  test "rejects optional fields that are not a trailing suffix" do
    with_fixture_dir(fn dir ->
      mutate_schema(dir, fn schema ->
        # `title` stays optional but the trailing `marked_count` becomes required:
        # an optional field now precedes a required one, which must be rejected.
        String.replace(
          schema,
          "{ name = \"marked_count\", type = \"u16\", optional = true }",
          "{ name = \"marked_count\", type = \"u16\" }",
          global: false
        )
      end)

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/must be a contiguous trailing suffix/, fn ->
          generate_fast([])
        end
      end)
    end)
  end

  test "rejects optional on a counted_array section field" do
    with_fixture_dir(fn dir ->
      mutate_schema(dir, fn schema ->
        String.replace(
          schema,
          "element = \"picker_item\"",
          "element = \"picker_item\"\nfields = [{ name = \"trailing\", type = \"u8\", optional = true }]",
          global: false
        )
      end)

      File.cd!(dir, fn ->
        assert_raise Mix.Error, ~r/not allowed on counted_array sections/, fn ->
          generate_fast([])
        end
      end)
    end)
  end

  @spec generate_fast([String.t()]) :: :ok
  defp generate_fast(args) do
    Minga.Mix.ProtocolGenerator.run(args, format_generated_go: false)
  end

  @spec with_fixture_dir((Path.t() -> any())) :: any()
  defp with_fixture_dir(fun) do
    dir = Path.join(System.tmp_dir!(), "protocol-gen-#{System.unique_integer([:positive])}")
    File.rm_rf!(dir)
    File.mkdir_p!(dir)
    copy_fixtures(dir)

    try do
      fun.(dir)
    after
      File.rm_rf!(dir)
    end
  end

  @spec copy_fixtures(Path.t()) :: :ok
  defp copy_fixtures(dir) do
    Enum.each(@fixture_paths, fn rel_path ->
      source = Path.join(@repo_root, rel_path)
      destination = Path.join(dir, rel_path)
      File.mkdir_p!(Path.dirname(destination))
      File.cp!(source, destination)
    end)

    :ok
  end

  @spec mutate_schema(Path.t(), (String.t() -> String.t())) :: :ok
  defp mutate_schema(dir, fun) do
    path = Path.join(dir, "docs/protocol_schema.toml")
    path |> File.read!() |> fun.() |> then(&File.write!(path, &1))
    :ok
  end
end
