package ui

// Conformance transcript runner (#2667).
//
// Executes the shared frontend conformance corpus (test/conformance/corpus)
// against the Go TUI's REAL protocol decoder, resident-window store, local
// presentation reconciler, and pointer normalization. The Swift suite executes
// the same corpus, so a divergence in store lifecycle or input resolution fails
// a build instead of surfacing as a rendering bug.
//
// The corpus is generated by `mix conformance.gen` from the real BEAM encoder.
// This runner never hand-builds wire bytes; it base64-decodes the fixtures and
// feeds them through protocol.DecodeCommand + Model.applyMutation.
//
// Transcripts marked go:false in index.json are the resident-only seams the Go
// TUI does not implement under its windowed contract (the scroll_seq discard).
// They are explicitly skipped-with-reason here, never silently omitted, so the
// resident-port child flips them on by decoding the corpus that already exists.

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"testing"

	tea "charm.land/bubbletea/v2"
	"github.com/jsmestad/minga/go/tui/internal/protocol"
)

const conformanceCorpusRel = "../../../../test/conformance/corpus"

type conformanceIndex struct {
	Version     int                     `json:"version"`
	Transcripts []conformanceIndexEntry `json:"transcripts"`
}

type conformanceIndexEntry struct {
	Name         string `json:"name"`
	Category     string `json:"category"`
	File         string `json:"file"`
	Swift        bool   `json:"swift"`
	Go           bool   `json:"go"`
	GoSkipReason string `json:"go_skip_reason"`
}

type conformanceTranscript struct {
	Name        string            `json:"name"`
	Category    string            `json:"category"`
	Description string            `json:"description"`
	Steps       []conformanceStep `json:"steps"`
}

type conformanceStep struct {
	Kind          string                    `json:"kind"`
	Fixture       *productionFixture        `json:"fixture"`
	Operations    []productionOperation     `json:"operations"`
	Opcode        int                       `json:"opcode"`
	Note          string                    `json:"note"`
	PayloadBase64 string                    `json:"payload_base64"`
	WindowID      uint16                    `json:"window_id"`
	RowOffset     int                       `json:"row_offset"`
	ColOffset     int                       `json:"col_offset"`
	PointerRow    int                       `json:"pointer_row"`
	PointerCol    int                       `json:"pointer_col"`
	Rows          int                       `json:"rows"`
	Go            *conformanceGoSelector    `json:"go"`
	Swift         *conformanceSwiftSelector `json:"swift"`
	Expect        *conformanceExpect        `json:"expect"`
}

type productionFixture struct {
	RowCount                int    `json:"row_count"`
	ComparisonRowCount      int    `json:"comparison_row_count"`
	WideTextBytes           int    `json:"wide_text_bytes"`
	VisibleRows             int    `json:"visible_rows"`
	OverscanRows            int    `json:"overscan_rows"`
	OrdinaryEditIndex       int    `json:"ordinary_edit_index"`
	StructuralEditIndex     int    `json:"structural_edit_index"`
	ContentEpoch            uint32 `json:"content_epoch"`
	StaleContentEpoch       uint32 `json:"stale_content_epoch"`
	RecoveryGeneration      uint32 `json:"recovery_generation"`
	StaleRecoveryGeneration uint32 `json:"stale_recovery_generation"`
	RowTextPrefix           string `json:"row_text_prefix"`
}

type productionOperation struct {
	Name         string `json:"name"`
	ExpectStatus string `json:"expect_status"`
	FullResets   int    `json:"full_resets"`
	Splices      int    `json:"splices"`
	ChangedRows  int    `json:"changed_rows"`
	IDsResolved  int    `json:"ids_resolved"`
}

type conformanceExpect struct {
	StorePresent         *bool                        `json:"store_present"`
	Rows                 *[]conformanceRow            `json:"rows"`
	Anchor               *conformanceAnchor           `json:"anchor"`
	CursorRow            *int                         `json:"cursor_row"`
	OffsetDiscarded      *bool                        `json:"offset_discarded"`
	NormalizedBufferLine *int                         `json:"normalized_buffer_line"`
	Transcript           *conformanceTranscriptExpect `json:"transcript"`
}

// conformanceTranscriptExpect is the resident agent-transcript store state after
// a 0x86 frame: the shared parity core both frontends assert identically.
type conformanceTranscriptExpect struct {
	Epoch      uint32   `json:"epoch"`
	Count      int      `json:"count"`
	Truncated  bool     `json:"truncated"`
	MessageIDs []uint32 `json:"message_ids"`
}

// conformanceGoSelector carries the Go-specific position assertions. Go owns a
// top-anchored scroll offset in the store, so its runner drives the pure
// scrollBy/resolveScroll functions with an explicit max_top and asserts the
// resulting offset and pin state (the Swift SwiftUI-native runner ignores this).
type conformanceGoSelector struct {
	MaxTop              int     `json:"max_top"`
	ExpectTopOffset     *int    `json:"expect_top_offset"`
	ExpectPinned        *bool   `json:"expect_pinned"`
	ExpectPinTransition *string `json:"expect_pin_transition"`
}

// conformanceSwiftSelector carries the Swift-specific position assertion (id at a
// store index). The Go runner ignores it; the id stability it captures is already
// implied by the shared message_ids assertion on the frames.
type conformanceSwiftSelector struct {
	AnchorIndex int    `json:"anchor_index"`
	AnchorID    uint32 `json:"anchor_id"`
}

type conformanceRow struct {
	RowID       string `json:"row_id"`
	ContentHash uint32 `json:"content_hash"`
	BufLine     uint32 `json:"buf_line"`
}

type conformanceAnchor struct {
	Top  uint32 `json:"top"`
	Left uint16 `json:"left"`
}

func TestConformanceTranscripts(t *testing.T) {
	index := loadConformanceIndex(t)
	if len(index.Transcripts) == 0 {
		t.Fatal("conformance corpus index is empty; run `mix conformance.gen`")
	}

	for _, entry := range index.Transcripts {
		entry := entry
		t.Run(entry.Name, func(t *testing.T) {
			if !entry.Go {
				// Enumerated-but-skipped is the deliverable; the resident-port
				// child flips these on by satisfying the existing expectation.
				t.Skipf("resident-only transcript, Go windowed contract: %s", entry.GoSkipReason)
			}
			transcript := loadConformanceTranscript(t, entry.File)
			runConformanceTranscript(t, transcript)
		})
	}
}

func runConformanceTranscript(t *testing.T, transcript conformanceTranscript) {
	t.Helper()
	model := New(80, 24, nil, nil)

	for i, step := range transcript.Steps {
		switch step.Kind {
		case "frame":
			applyConformanceFrame(t, &model, i, step)
		case "production_fixture":
			applyProductionFixture(t, &model, i, step)
		case "inject_offset":
			injectConformanceOffset(&model, step)
		case "pointer":
			assertConformancePointer(t, &model, i, step)
		case "transcript_frame":
			applyConformanceTranscriptFrame(t, &model, i, step)
		case "transcript_scroll":
			applyConformanceTranscriptScroll(t, &model, i, step)
		case "transcript_assert":
			assertConformanceTranscriptPosition(t, &model, i, step)
		default:
			t.Fatalf("step %d: unknown kind %q", i, step.Kind)
		}
	}
}

func applyProductionFixture(t *testing.T, model *Model, i int, step conformanceStep) {
	t.Helper()
	fixture := step.Fixture
	if fixture == nil {
		t.Fatalf("step %d: production fixture descriptor missing", i)
	}
	if fixture.RowCount != 65_536 || fixture.WideTextBytes <= 65_535 {
		t.Fatalf("step %d: production boundaries = rows %d bytes %d", i, fixture.RowCount, fixture.WideTextBytes)
	}
	wide := make([]byte, fixture.WideTextBytes)
	for j := range wide {
		wide[j] = 'w'
	}
	rows := make([]protocol.WindowRow, fixture.RowCount)
	for row := range rows {
		text := fixture.RowTextPrefix + strconv.Itoa(row)
		if row == 0 {
			text = string(wide)
		}
		rows[row] = protocol.WindowRow{ID: uint64(row + 1), BufferLine: uint32(row), ContentHash: uint32(row + 1), Text: text}
	}
	applyProductionFrame(model, 1, 0, fixture.RecoveryGeneration,
		testThemeCommand(), protocol.Command{Kind: protocol.CommandWindowContent, Window: protocol.WindowContent{
			ID: 1, ContentEpoch: fixture.ContentEpoch, Rows: rows,
		}})
	observed := map[string]productionStatus{"keyframe": statusFromOutcome(model.lastFrameOutcome)}
	if got := model.residentRows[1].count(); got != fixture.RowCount {
		t.Fatalf("step %d: keyframe rows = %d, want %d", i, got, fixture.RowCount)
	}
	first, _ := model.residentRows[1].get(0)
	if len(first.Text) != fixture.WideTextBytes {
		t.Fatalf("step %d: wide carrier did not survive", i)
	}

	model.renderWork.reset()
	edit := rows[fixture.OrdinaryEditIndex]
	edit.ContentHash++
	edit.Text = "edited"
	applyProductionFrame(model, 2, 1, fixture.RecoveryGeneration,
		protocol.Command{Kind: protocol.CommandWindowDelta, Window: protocol.WindowContent{
			ID: 1, ContentEpoch: fixture.ContentEpoch, BaseRowCount: uint32(fixture.RowCount), ResultRowCount: uint32(fixture.RowCount),
			RowSplicesSet: true, RowSplices: []protocol.WindowRowSplice{{StartIndex: uint32(fixture.OrdinaryEditIndex), DeleteCount: 1, InsertRows: []protocol.WindowRow{edit}}},
		}})
	observed["ordinary_edit"] = statusFromOutcome(model.lastFrameOutcome)
	if model.renderWork.rowUpdates != 1 || model.renderWork.rowsFetched > 8 {
		t.Fatalf("step %d: ordinary production work = %+v", i, *model.renderWork)
	}
	gotEdit, _ := model.residentRows[1].get(fixture.OrdinaryEditIndex)
	if got := gotEdit; got.ContentHash != edit.ContentHash || got.Text != "edited" {
		t.Fatalf("step %d: ordinary splice was not applied", i)
	}

	inserted := protocol.WindowRow{ID: ^uint64(1), BufferLine: uint32(fixture.StructuralEditIndex), ContentHash: 0xA11CE, Text: "inserted-near-start"}
	applyProductionFrame(model, 3, 2, fixture.RecoveryGeneration,
		protocol.Command{Kind: protocol.CommandWindowDelta, Window: protocol.WindowContent{
			ID: 1, ContentEpoch: fixture.ContentEpoch, BaseRowCount: uint32(fixture.RowCount), ResultRowCount: uint32(fixture.RowCount + 1),
			RowSplicesSet: true, RowSplices: []protocol.WindowRowSplice{{StartIndex: uint32(fixture.StructuralEditIndex), InsertRows: []protocol.WindowRow{inserted}}},
		}})
	observed["structural_edit_near_start"] = statusFromOutcome(model.lastFrameOutcome)
	gotInserted, _ := model.residentRows[1].get(fixture.StructuralEditIndex)
	if got := gotInserted.ID; got != inserted.ID {
		t.Fatalf("step %d: near-start structural splice id = %d", i, got)
	}

	retainedIndex := fixture.OrdinaryEditIndex + 1 // insertion shifted the edited row right
	retained, _ := model.residentRows[1].get(retainedIndex)
	applyProductionFrame(model, 4, 3, fixture.RecoveryGeneration,
		protocol.Command{Kind: protocol.CommandWindowDelta, Window: protocol.WindowContent{
			ID: 1, ContentEpoch: fixture.ContentEpoch, BaseRowCount: uint32(fixture.RowCount + 1), ResultRowCount: uint32(fixture.RowCount + 1),
			RowSplicesSet: true, RowSplices: []protocol.WindowRowSplice{{StartIndex: uint32(retainedIndex), DeleteCount: 1, InsertRows: []protocol.WindowRow{{Ref: true, ID: retained.ID, ContentHash: retained.ContentHash}}}},
		}})
	observed["retained_reference"] = statusFromOutcome(model.lastFrameOutcome)
	gotRetained, _ := model.residentRows[1].get(retainedIndex)
	if got := gotRetained; got.ID != retained.ID || got.ContentHash != retained.ContentHash {
		t.Fatalf("step %d: retained reference did not resolve", i)
	}

	if fixture.StaleContentEpoch >= fixture.ContentEpoch || fixture.StaleRecoveryGeneration >= fixture.RecoveryGeneration {
		t.Fatalf("step %d: stale epoch/generation descriptor is not stale", i)
	}
	beforeCount := model.residentRows[1].count()
	applyProductionFrame(model, 5, 4, fixture.RecoveryGeneration,
		protocol.Command{Kind: protocol.CommandWindowDelta, Window: protocol.WindowContent{
			ID: 1, ContentEpoch: fixture.ContentEpoch, BaseRowCount: uint32(fixture.RowCount + 1), ResultRowCount: 1,
			RowSplicesSet: true, RowSplices: []protocol.WindowRowSplice{{StartIndex: 0, DeleteCount: uint32(fixture.RowCount + 1), InsertRows: []protocol.WindowRow{{Ref: true, ID: ^uint64(0), ContentHash: 1}}}},
		}})
	observed["reference_miss"] = statusFromOutcome(model.lastFrameOutcome)
	if model.residentRows[1].count() != beforeCount {
		t.Fatalf("step %d: ref miss changed committed rows", i)
	}

	applyProductionFrame(model, 6, 4, fixture.RecoveryGeneration,
		protocol.Command{Kind: protocol.CommandWindowDelta, Window: protocol.WindowContent{
			ID: 1, ContentEpoch: fixture.StaleContentEpoch, Rows: []protocol.WindowRow{{Ref: true, ID: 1, ContentHash: 1}},
		}})
	observed["stale_content_epoch"] = statusFromOutcome(model.lastFrameOutcome)
	if model.residentRows[1].count() != beforeCount {
		t.Fatalf("step %d: stale epoch changed committed rows", i)
	}

	applyProductionFrame(model, 7, 4, fixture.StaleRecoveryGeneration,
		windowRowsCommand(1, "must-not-publish"))
	observed["stale_recovery_generation"] = statusFromOutcome(model.lastFrameOutcome)

	applyProductionFrame(model, 8, 0, fixture.RecoveryGeneration,
		testThemeCommand(), protocol.Command{Kind: protocol.CommandWindowContent, Window: protocol.WindowContent{
			ID: 1, ContentEpoch: fixture.ContentEpoch + 1, Rows: rows,
		}})
	observed["reset_full_recovery"] = statusFromOutcome(model.lastFrameOutcome)
	if model.residentRows[1].count() != fixture.RowCount {
		t.Fatalf("step %d: reset recovery count mismatch", i)
	}
	for _, operation := range step.Operations {
		if got := observed[operation.Name].String(); got != operation.ExpectStatus {
			t.Fatalf("step %d: %s production status %q, want %q", i, operation.Name, got, operation.ExpectStatus)
		}
	}
}

type productionStatus byte

const (
	productionUnknown productionStatus = iota
	productionAccepted
	productionRecoveryRequired
	productionStaleDiscarded
)

func (s productionStatus) String() string {
	switch s {
	case productionAccepted:
		return "accepted"
	case productionRecoveryRequired:
		return "recovery_required"
	case productionStaleDiscarded:
		return "stale_discarded"
	default:
		return "unknown"
	}
}

func statusFromOutcome(outcome frameOutcome) productionStatus {
	switch outcome {
	case frameOutcomeApplied:
		return productionAccepted
	case frameOutcomeRecoveryRequired:
		return productionRecoveryRequired
	case frameOutcomeStale, frameOutcomeRejected:
		return productionStaleDiscarded
	default:
		return productionUnknown
	}
}

func applyProductionFrame(model *Model, seq, base, generation uint32, commands ...protocol.Command) {
	begin := protocol.Command{Kind: protocol.CommandBeginFrame, FrameSeq: seq, BaseFrameSeq: base, Generation: generation}
	model.applyCommands(append(append([]protocol.Command{begin}, commands...), protocol.Command{Kind: protocol.CommandCommitFrame, FrameSeq: seq}))
}

func operationCount(operations []productionOperation, name, field string) int {
	for _, operation := range operations {
		if operation.Name != name {
			continue
		}
		switch field {
		case "full_resets":
			return operation.FullResets
		case "splices":
			return operation.Splices
		case "changed_rows":
			return operation.ChangedRows
		case "ids_resolved":
			return operation.IDsResolved
		}
	}
	return 0
}

func applyConformanceFrame(t *testing.T, model *Model, i int, step conformanceStep) {
	t.Helper()
	payload, err := base64.StdEncoding.DecodeString(step.PayloadBase64)
	if err != nil {
		t.Fatalf("step %d (%s): base64 decode: %v", i, step.Note, err)
	}
	command, err := protocol.DecodeCommand(payload)
	if err != nil {
		t.Fatalf("step %d (%s): DecodeCommand: %v", i, step.Note, err)
	}

	windowID := command.Window.ID
	_, offsetBefore := model.localPresentation.scrolls[windowID]

	model.applyMutation(command)

	if step.Expect == nil {
		return
	}
	assertConformanceFrame(t, model, i, step, windowID, offsetBefore)
}

func assertConformanceFrame(t *testing.T, model *Model, i int, step conformanceStep, windowID uint16, offsetBefore bool) {
	t.Helper()
	expect := step.Expect
	window, present := model.windows[windowID]

	if expect.StorePresent != nil && present != *expect.StorePresent {
		t.Fatalf("step %d (%s): store_present = %v, want %v", i, step.Note, present, *expect.StorePresent)
	}

	if expect.Rows != nil {
		assertConformanceRows(t, i, step, window.Rows, *expect.Rows)
	}

	if expect.Anchor != nil {
		if window.Scroll.AnchorTop != expect.Anchor.Top || window.Scroll.AnchorLeft != expect.Anchor.Left {
			t.Fatalf("step %d (%s): anchor = {top:%d left:%d}, want {top:%d left:%d}",
				i, step.Note, window.Scroll.AnchorTop, window.Scroll.AnchorLeft, expect.Anchor.Top, expect.Anchor.Left)
		}
	}

	if expect.CursorRow != nil && int(window.CursorRow) != *expect.CursorRow {
		t.Fatalf("step %d (%s): cursor_row = %d, want %d", i, step.Note, window.CursorRow, *expect.CursorRow)
	}

	if expect.OffsetDiscarded != nil {
		_, offsetAfter := model.localPresentation.scrolls[windowID]
		discarded := offsetBefore && !offsetAfter
		if discarded != *expect.OffsetDiscarded {
			t.Fatalf("step %d (%s): offset_discarded = %v, want %v (offset before=%v after=%v)",
				i, step.Note, discarded, *expect.OffsetDiscarded, offsetBefore, offsetAfter)
		}
	}
}

func assertConformanceRows(t *testing.T, i int, step conformanceStep, got []protocol.WindowRow, want []conformanceRow) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("step %d (%s): resident row count = %d, want %d", i, step.Note, len(got), len(want))
	}
	for j, wantRow := range want {
		wantID, err := strconv.ParseUint(wantRow.RowID, 10, 64)
		if err != nil {
			t.Fatalf("step %d (%s): row %d id parse: %v", i, step.Note, j, err)
		}
		g := got[j]
		if g.ID != wantID || g.ContentHash != wantRow.ContentHash || g.BufferLine != wantRow.BufLine {
			t.Fatalf("step %d (%s): row %d = {id:%d hash:%d line:%d}, want {id:%d hash:%d line:%d}",
				i, step.Note, j, g.ID, g.ContentHash, g.BufferLine, wantID, wantRow.ContentHash, wantRow.BufLine)
		}
	}
}

func injectConformanceOffset(model *Model, step conformanceStep) {
	// State injection (the point of the input suite): set a nonzero local offset
	// mid-transcript with anchor keys matching the currently-stored frame, so the
	// reconciler compares it against the next committed frame's keys.
	window := model.windows[step.WindowID]
	model.localPresentation.scrolls[step.WindowID] = presentationScroll{
		anchorTop:        window.Scroll.AnchorTop,
		anchorLeft:       window.Scroll.AnchorLeft,
		contentEpoch:     window.Scroll.ContentEpoch,
		layoutGeneration: window.Scroll.LayoutGeneration,
		// Capture the scroll_seq the currently-stored frame carries so a
		// later strictly-newer scroll_seq forces a discard, exactly as a real
		// wheel offset captures the committed seq at creation time (#2671).
		scrollSeq: window.Scroll.ScrollSeq,
		rowOffset: step.RowOffset,
		colOffset: step.ColOffset,
	}
}

func assertConformancePointer(t *testing.T, model *Model, i int, step conformanceStep) {
	t.Helper()
	window := model.windows[step.WindowID]
	anchorTop := int(window.Scroll.AnchorTop)

	// Drive the real pointer path: mousePacket -> normalizePresentationMouse.
	// mousePacket subtracts the header height (input.go), so the encoded row is
	// body-relative: body row 0 is the window's top visible line, i.e. anchorTop.
	headerHeight := model.layout.header.Height
	packet, ok := model.mousePacket(tea.MouseClickMsg(tea.Mouse{
		X:      step.PointerCol,
		Y:      headerHeight + step.PointerRow,
		Button: tea.MouseLeft,
	}))
	if !ok {
		t.Fatalf("step %d (%s): pointer did not encode a mouse packet", i, step.Note)
	}

	normalizedBodyRow := int(mouseRow(packet))
	bufferLine := anchorTop + normalizedBodyRow

	if step.Expect != nil && step.Expect.NormalizedBufferLine != nil {
		if bufferLine != *step.Expect.NormalizedBufferLine {
			t.Fatalf("step %d (%s): normalized_buffer_line = %d, want %d",
				i, step.Note, bufferLine, *step.Expect.NormalizedBufferLine)
		}
	}
}

// applyConformanceTranscriptFrame decodes a 0x86 gui_agent_transcript frame and
// folds it through the real store (protocol.DecodeCommand + model.applyMutation ->
// residentTranscript.apply), then asserts the resident store's epoch, truncated
// flag, count, and ordered message ids. This is the shared parity assertion the
// Swift runner mirrors byte-for-byte.
func applyConformanceTranscriptFrame(t *testing.T, model *Model, i int, step conformanceStep) {
	t.Helper()
	payload, err := base64.StdEncoding.DecodeString(step.PayloadBase64)
	if err != nil {
		t.Fatalf("step %d (%s): base64 decode: %v", i, step.Note, err)
	}
	command, err := protocol.DecodeCommand(payload)
	if err != nil {
		t.Fatalf("step %d (%s): DecodeCommand: %v", i, step.Note, err)
	}
	model.applyMutation(command)

	if step.Expect == nil || step.Expect.Transcript == nil {
		return
	}
	want := step.Expect.Transcript
	store := model.transcript

	if store.epoch != want.Epoch {
		t.Fatalf("step %d (%s): epoch = %d, want %d", i, step.Note, store.epoch, want.Epoch)
	}
	if store.truncated != want.Truncated {
		t.Fatalf("step %d (%s): truncated = %v, want %v", i, step.Note, store.truncated, want.Truncated)
	}

	ids := make([]uint32, len(store.messages))
	for j := range store.messages {
		ids[j] = store.messages[j].ID
	}
	if len(ids) != want.Count {
		t.Fatalf("step %d (%s): resident count = %d, want %d", i, step.Note, len(ids), want.Count)
	}
	if !equalIDs(ids, want.MessageIDs) {
		t.Fatalf("step %d (%s): resident ids = %v, want %v", i, step.Note, ids, want.MessageIDs)
	}
}

// applyConformanceTranscriptScroll drives the real local-scroll path
// (scrollBy + resolveScroll) and asserts the resulting top-anchored offset, pin
// state, and pin transition. This is the Go offset model; the Swift runner treats
// the scroll input as a view-only concern with no store effect.
func applyConformanceTranscriptScroll(t *testing.T, model *Model, i int, step conformanceStep) {
	t.Helper()
	store := model.transcript
	store.scrollBy(step.Rows)

	maxTop := 0
	if step.Go != nil {
		maxTop = step.Go.MaxTop
	}
	transition := store.resolveScroll(maxTop)
	assertConformanceGoSelector(t, i, step, store, transition)
}

// assertConformanceTranscriptPosition drives resolveScroll once more (no queued
// scroll) at the post-frame max_top and asserts the reading offset is stable and
// the pin state is correct. It is the Go leg of the per-frontend position
// assertion; the Swift runner asserts an anchor id instead.
func assertConformanceTranscriptPosition(t *testing.T, model *Model, i int, step conformanceStep) {
	t.Helper()
	if step.Go == nil {
		return
	}
	store := model.transcript
	transition := store.resolveScroll(step.Go.MaxTop)
	assertConformanceGoSelector(t, i, step, store, transition)
}

func assertConformanceGoSelector(t *testing.T, i int, step conformanceStep, store *residentTranscript, transition int) {
	t.Helper()
	sel := step.Go
	if sel == nil {
		return
	}
	if sel.ExpectTopOffset != nil && store.topOffset != *sel.ExpectTopOffset {
		t.Fatalf("step %d (%s): top_offset = %d, want %d", i, step.Note, store.topOffset, *sel.ExpectTopOffset)
	}
	if sel.ExpectPinned != nil && store.pinned != *sel.ExpectPinned {
		t.Fatalf("step %d (%s): pinned = %v, want %v", i, step.Note, store.pinned, *sel.ExpectPinned)
	}
	if sel.ExpectPinTransition != nil {
		want := pinTransitionFromName(*sel.ExpectPinTransition)
		if transition != want {
			t.Fatalf("step %d (%s): pin_transition = %d, want %d (%q)", i, step.Note, transition, want, *sel.ExpectPinTransition)
		}
	}
}

func pinTransitionFromName(name string) int {
	switch name {
	case "scrolled_away":
		return pinScrolledAway
	case "returned":
		return pinReturned
	default:
		return pinNone
	}
}

func equalIDs(a []uint32, b []uint32) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func loadConformanceIndex(t *testing.T) conformanceIndex {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(conformanceCorpusRel, "index.json"))
	if err != nil {
		t.Fatalf("read conformance index: %v", err)
	}
	var index conformanceIndex
	if err := json.Unmarshal(raw, &index); err != nil {
		t.Fatalf("parse conformance index: %v", err)
	}
	return index
}

func loadConformanceTranscript(t *testing.T, file string) conformanceTranscript {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(conformanceCorpusRel, file))
	if err != nil {
		t.Fatalf("read transcript %s: %v", file, err)
	}
	var transcript conformanceTranscript
	if err := json.Unmarshal(raw, &transcript); err != nil {
		t.Fatalf("parse transcript %s: %v", file, err)
	}
	return transcript
}
