package ui

// Conformance transcript runner (#2667).
//
// Executes the shared frontend conformance corpus (test/conformance/corpus)
// against the Go TUI's REAL protocol decoder, resident-window store, local
// presentation reconciler, and pointer normalization. The Swift suite executes
// the same corpus, so a divergence in store lifecycle or input resolution fails
// a build instead of surfacing as a rendering bug.
//
// The corpus is generated by `mix conformance.gen` from the real BEAM encoder.
// This runner never hand-builds wire bytes; it base64-decodes the fixtures and
// feeds them through protocol.DecodeCommand + Model.applyMutation.
//
// Transcripts marked go:false in index.json are the resident-only seams the Go
// TUI does not implement under its windowed contract (the scroll_seq discard).
// They are explicitly skipped-with-reason here, never silently omitted, so the
// resident-port child flips them on by decoding the corpus that already exists.

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"testing"

	tea "charm.land/bubbletea/v2"
	"github.com/jsmestad/minga/go/tui/internal/protocol"
)

const conformanceCorpusRel = "../../../../test/conformance/corpus"

type conformanceIndex struct {
	Version     int                     `json:"version"`
	Transcripts []conformanceIndexEntry `json:"transcripts"`
}

type conformanceIndexEntry struct {
	Name         string `json:"name"`
	Category     string `json:"category"`
	File         string `json:"file"`
	Swift        bool   `json:"swift"`
	Go           bool   `json:"go"`
	GoSkipReason string `json:"go_skip_reason"`
}

type conformanceTranscript struct {
	Name        string            `json:"name"`
	Category    string            `json:"category"`
	Description string            `json:"description"`
	Steps       []conformanceStep `json:"steps"`
}

type conformanceStep struct {
	Kind          string             `json:"kind"`
	Opcode        int                `json:"opcode"`
	Note          string             `json:"note"`
	PayloadBase64 string             `json:"payload_base64"`
	WindowID      uint16             `json:"window_id"`
	RowOffset     int                `json:"row_offset"`
	ColOffset     int                `json:"col_offset"`
	PointerRow    int                `json:"pointer_row"`
	PointerCol    int                `json:"pointer_col"`
	Expect        *conformanceExpect `json:"expect"`
}

type conformanceExpect struct {
	StorePresent         *bool              `json:"store_present"`
	Rows                 *[]conformanceRow  `json:"rows"`
	Anchor               *conformanceAnchor `json:"anchor"`
	CursorRow            *int               `json:"cursor_row"`
	OffsetDiscarded      *bool              `json:"offset_discarded"`
	NormalizedBufferLine *int               `json:"normalized_buffer_line"`
}

type conformanceRow struct {
	RowID       string `json:"row_id"`
	ContentHash uint32 `json:"content_hash"`
	BufLine     uint32 `json:"buf_line"`
}

type conformanceAnchor struct {
	Top  uint32 `json:"top"`
	Left uint16 `json:"left"`
}

func TestConformanceTranscripts(t *testing.T) {
	index := loadConformanceIndex(t)
	if len(index.Transcripts) == 0 {
		t.Fatal("conformance corpus index is empty; run `mix conformance.gen`")
	}

	for _, entry := range index.Transcripts {
		entry := entry
		t.Run(entry.Name, func(t *testing.T) {
			if !entry.Go {
				// Enumerated-but-skipped is the deliverable; the resident-port
				// child flips these on by satisfying the existing expectation.
				t.Skipf("resident-only transcript, Go windowed contract: %s", entry.GoSkipReason)
			}
			transcript := loadConformanceTranscript(t, entry.File)
			runConformanceTranscript(t, transcript)
		})
	}
}

func runConformanceTranscript(t *testing.T, transcript conformanceTranscript) {
	t.Helper()
	model := New(80, 24, nil, nil)

	for i, step := range transcript.Steps {
		switch step.Kind {
		case "frame":
			applyConformanceFrame(t, &model, i, step)
		case "inject_offset":
			injectConformanceOffset(&model, step)
		case "pointer":
			assertConformancePointer(t, &model, i, step)
		default:
			t.Fatalf("step %d: unknown kind %q", i, step.Kind)
		}
	}
}

func applyConformanceFrame(t *testing.T, model *Model, i int, step conformanceStep) {
	t.Helper()
	payload, err := base64.StdEncoding.DecodeString(step.PayloadBase64)
	if err != nil {
		t.Fatalf("step %d (%s): base64 decode: %v", i, step.Note, err)
	}
	command, err := protocol.DecodeCommand(payload)
	if err != nil {
		t.Fatalf("step %d (%s): DecodeCommand: %v", i, step.Note, err)
	}

	windowID := command.Window.ID
	_, offsetBefore := model.localPresentation.scrolls[windowID]

	model.applyMutation(command)

	if step.Expect == nil {
		return
	}
	assertConformanceFrame(t, model, i, step, windowID, offsetBefore)
}

func assertConformanceFrame(t *testing.T, model *Model, i int, step conformanceStep, windowID uint16, offsetBefore bool) {
	t.Helper()
	expect := step.Expect
	window, present := model.windows[windowID]

	if expect.StorePresent != nil && present != *expect.StorePresent {
		t.Fatalf("step %d (%s): store_present = %v, want %v", i, step.Note, present, *expect.StorePresent)
	}

	if expect.Rows != nil {
		assertConformanceRows(t, i, step, window.Rows, *expect.Rows)
	}

	if expect.Anchor != nil {
		if window.Scroll.AnchorTop != expect.Anchor.Top || window.Scroll.AnchorLeft != expect.Anchor.Left {
			t.Fatalf("step %d (%s): anchor = {top:%d left:%d}, want {top:%d left:%d}",
				i, step.Note, window.Scroll.AnchorTop, window.Scroll.AnchorLeft, expect.Anchor.Top, expect.Anchor.Left)
		}
	}

	if expect.CursorRow != nil && int(window.CursorRow) != *expect.CursorRow {
		t.Fatalf("step %d (%s): cursor_row = %d, want %d", i, step.Note, window.CursorRow, *expect.CursorRow)
	}

	if expect.OffsetDiscarded != nil {
		_, offsetAfter := model.localPresentation.scrolls[windowID]
		discarded := offsetBefore && !offsetAfter
		if discarded != *expect.OffsetDiscarded {
			t.Fatalf("step %d (%s): offset_discarded = %v, want %v (offset before=%v after=%v)",
				i, step.Note, discarded, *expect.OffsetDiscarded, offsetBefore, offsetAfter)
		}
	}
}

func assertConformanceRows(t *testing.T, i int, step conformanceStep, got []protocol.WindowRow, want []conformanceRow) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("step %d (%s): resident row count = %d, want %d", i, step.Note, len(got), len(want))
	}
	for j, wantRow := range want {
		wantID, err := strconv.ParseUint(wantRow.RowID, 10, 64)
		if err != nil {
			t.Fatalf("step %d (%s): row %d id parse: %v", i, step.Note, j, err)
		}
		g := got[j]
		if g.ID != wantID || g.ContentHash != wantRow.ContentHash || g.BufferLine != wantRow.BufLine {
			t.Fatalf("step %d (%s): row %d = {id:%d hash:%d line:%d}, want {id:%d hash:%d line:%d}",
				i, step.Note, j, g.ID, g.ContentHash, g.BufferLine, wantID, wantRow.ContentHash, wantRow.BufLine)
		}
	}
}

func injectConformanceOffset(model *Model, step conformanceStep) {
	// State injection (the point of the input suite): set a nonzero local offset
	// mid-transcript with anchor keys matching the currently-stored frame, so the
	// reconciler compares it against the next committed frame's keys.
	window := model.windows[step.WindowID]
	model.localPresentation.scrolls[step.WindowID] = presentationScroll{
		anchorTop:        window.Scroll.AnchorTop,
		anchorLeft:       window.Scroll.AnchorLeft,
		contentEpoch:     window.Scroll.ContentEpoch,
		layoutGeneration: window.Scroll.LayoutGeneration,
		rowOffset:        step.RowOffset,
		colOffset:        step.ColOffset,
	}
}

func assertConformancePointer(t *testing.T, model *Model, i int, step conformanceStep) {
	t.Helper()
	window := model.windows[step.WindowID]
	anchorTop := int(window.Scroll.AnchorTop)

	// Drive the real pointer path: mousePacket -> normalizePresentationMouse.
	// mousePacket subtracts the header height (input.go), so the encoded row is
	// body-relative: body row 0 is the window's top visible line, i.e. anchorTop.
	headerHeight := model.layout.header.Height
	packet, ok := model.mousePacket(tea.MouseClickMsg(tea.Mouse{
		X:      step.PointerCol,
		Y:      headerHeight + step.PointerRow,
		Button: tea.MouseLeft,
	}))
	if !ok {
		t.Fatalf("step %d (%s): pointer did not encode a mouse packet", i, step.Note)
	}

	normalizedBodyRow := int(mouseRow(packet))
	bufferLine := anchorTop + normalizedBodyRow

	if step.Expect != nil && step.Expect.NormalizedBufferLine != nil {
		if bufferLine != *step.Expect.NormalizedBufferLine {
			t.Fatalf("step %d (%s): normalized_buffer_line = %d, want %d",
				i, step.Note, bufferLine, *step.Expect.NormalizedBufferLine)
		}
	}
}

func loadConformanceIndex(t *testing.T) conformanceIndex {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(conformanceCorpusRel, "index.json"))
	if err != nil {
		t.Fatalf("read conformance index: %v", err)
	}
	var index conformanceIndex
	if err := json.Unmarshal(raw, &index); err != nil {
		t.Fatalf("parse conformance index: %v", err)
	}
	return index
}

func loadConformanceTranscript(t *testing.T, file string) conformanceTranscript {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(conformanceCorpusRel, file))
	if err != nil {
		t.Fatalf("read transcript %s: %v", file, err)
	}
	var transcript conformanceTranscript
	if err := json.Unmarshal(raw, &transcript); err != nil {
		t.Fatalf("parse transcript %s: %v", file, err)
	}
	return transcript
}
